In [156]:
%load_ext autoreload
%autoreload 2
from IPython.display import display
from pkdb_analysis import PKFilter, PKFilterFactory, PKData

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [157]:
# get all data and store as hdf5
#data = pka.PKDBData.from_db()
#data.to_hdf5("pkdb_all.h5")

In [177]:
# data with filters
pkfilter = PKFilterFactory.by_study_name("Test1")
data = PKData.from_db(pkfilter=pkfilter)

pkfilter = PKFilterFactory.by_study_sid("PKDB99999")
data = PKData.from_db(pkfilter=pkfilter)

data.print_choices("groups")

WARNING:root:*** Querying data ***
WARNING:root:http://0.0.0.0:8000/api/v1/interventions_elastic/?format=json&page_size=2000&normed=true&study_name=Test1
WARNING:root:http://0.0.0.0:8000/api/v1/interventions_elastic/?format=json&page_size=2000&normed=true&study_name=Test1&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_individuals/?format=json&page_size=2000&study_name=Test1
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_individuals/?format=json&page_size=2000&study_name=Test1&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_groups/?format=json&page_size=2000&study_name=Test1
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_groups/?format=json&page_size=2000&study_name=Test1&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true&study_name=Test1
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true&study_name=Test1&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/timecourse_intervention/?format=json&page_size=2000&normed=true&study_name=Test1
WARNING:root:http://0.0.0.0:8000/api/v1/timecourse_intervention/?format=json&page_size=2000&normed=true&study_name=Test1&page=1
WARNING:root:Calculating choices
WARNING:root:Consice DataFrames
WARNING:root:*** Querying data ***
WARNING:root:http://0.0.0.0:8000/api/v1/interventions_elastic/?format=json&page_size=2000&normed=true&pk__in=89__90__92
WARNING:root:http://0.0.0.0:8000/api/v1/interventions_elastic/?format=json&page_size=2000&normed=true&pk__in=89__90__92&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_individuals/?format=json&page_size=2000&individual_pk__in=69__72__70__71__67__68
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_individuals/?format=json&page_size=2000&individual_pk__in=69__72__70__71__67__68&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_groups/?format=json&page_size=2000&group_pk__in=14
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_groups/?format=json&page_size=2000&group_pk__in=14&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true&output_pk__in=1944__1943__1920__1901__1879__1876__1863__1862__1860__1852__1961__1957__1907__1903__1894__1886__1885__1884__1865__1864__1854__1838__1836__1845__1900__1899__1880__1878__1850__1849__1831__1959__1908__1905__1896__1883__1881__1867__1853__1872__1847__1945__1942__1922__1921__1898__1891__1888__1887__1877__1835__1956__1929__1928__1927__1897__1869__1857__1856__1871__1844__1946__1941__1923__1902__1834__1962__1960__1955__1926__1925__1906__1895__1868__1855__1874__1843__1842__1940__1939__1924__1890__1889__1861__1859__1851__1848__1833__1832__1958__1930__1904__1893__1892__1882__1866__1858__1841__1840__1839__1837__1875__1873__1870__1846
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true&output_pk__in=1944__1943__1920__1901__1879__1876__1863__1862__1860__1852__1961__1957__1907__1903__1894__1886__1885__1884__1865__1864__1854__1838__1836__1845__1900__1899__1880__1878__1850__1849__1831__1959__1908__1905__1896__1883__1881__1867__1853__1872__1847__1945__1942__1922__1921__1898__1891__1888__1887__1877__1835__1956__1929__1928__1927__1897__1869__1857__1856__1871__1844__1946__1941__1923__1902__1834__1962__1960__1955__1926__1925__1906__1895__1868__1855__1874__1843__1842__1940__1939__1924__1890__1889__1861__1859__1851__1848__1833__1832__1958__1930__1904__1893__1892__1882__1866__1858__1841__1840__1839__1837__1875__1873__1870__1846&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/timecourse_intervention/?format=json&page_size=2000&normed=true&timecourse_pk__in=49__50
WARNING:root:http://0.0.0.0:8000/api/v1/timecourse_intervention/?format=json&page_size=2000&normed=true&timecourse_pk__in=49__50&page=1
WARNING:root:Calculating choices
WARNING:root:*** Querying data ***
WARNING:root:http://0.0.0.0:8000/api/v1/interventions_elastic/?format=json&page_size=2000&normed=true&study_sid=PKDB99999
WARNING:root:http://0.0.0.0:8000/api/v1/interventions_elastic/?format=json&page_size=2000&normed=true&study_sid=PKDB99999&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_individuals/?format=json&page_size=2000&study_sid=PKDB99999
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_individuals/?format=json&page_size=2000&study_sid=PKDB99999&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_groups/?format=json&page_size=2000&study_sid=PKDB99999
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_groups/?format=json&page_size=2000&study_sid=PKDB99999&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true&study_sid=PKDB99999
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true&study_sid=PKDB99999&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/timecourse_intervention/?format=json&page_size=2000&normed=true&study_sid=PKDB99999
WARNING:root:http://0.0.0.0:8000/api/v1/timecourse_intervention/?format=json&page_size=2000&normed=true&study_sid=PKDB99999&page=1
WARNING:root:Calculating choices
WARNING:root:Consice DataFrames
WARNING:root:*** Querying data ***
WARNING:root:http://0.0.0.0:8000/api/v1/interventions_elastic/?format=json&page_size=2000&normed=true&pk__in=89__90__92
WARNING:root:http://0.0.0.0:8000/api/v1/interventions_elastic/?format=json&page_size=2000&normed=true&pk__in=89__90__92&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_individuals/?format=json&page_size=2000&individual_pk__in=69__72__70__71__67__68
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_individuals/?format=json&page_size=2000&individual_pk__in=69__72__70__71__67__68&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_groups/?format=json&page_size=2000&group_pk__in=14
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_groups/?format=json&page_size=2000&group_pk__in=14&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true&output_pk__in=1944__1943__1920__1901__1879__1876__1863__1862__1860__1852__1961__1957__1907__1903__1894__1886__1885__1884__1865__1864__1854__1838__1836__1845__1900__1899__1880__1878__1850__1849__1831__1959__1908__1905__1896__1883__1881__1867__1853__1872__1847__1945__1942__1922__1921__1898__1891__1888__1887__1877__1835__1956__1929__1928__1927__1897__1869__1857__1856__1871__1844__1946__1941__1923__1902__1834__1962__1960__1955__1926__1925__1906__1895__1868__1855__1874__1843__1842__1940__1939__1924__1890__1889__1861__1859__1851__1848__1833__1832__1958__1930__1904__1893__1892__1882__1866__1858__1841__1840__1839__1837__1875__1873__1870__1846
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true&output_pk__in=1944__1943__1920__1901__1879__1876__1863__1862__1860__1852__1961__1957__1907__1903__1894__1886__1885__1884__1865__1864__1854__1838__1836__1845__1900__1899__1880__1878__1850__1849__1831__1959__1908__1905__1896__1883__1881__1867__1853__1872__1847__1945__1942__1922__1921__1898__1891__1888__1887__1877__1835__1956__1929__1928__1927__1897__1869__1857__1856__1871__1844__1946__1941__1923__1902__1834__1962__1960__1955__1926__1925__1906__1895__1868__1855__1874__1843__1842__1940__1939__1924__1890__1889__1861__1859__1851__1848__1833__1832__1958__1930__1904__1893__1892__1882__1866__1858__1841__1840__1839__1837__1875__1873__1870__1846&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/timecourse_intervention/?format=json&page_size=2000&normed=true&timecourse_pk__in=49__50
WARNING:root:http://0.0.0.0:8000/api/v1/timecourse_intervention/?format=json&page_size=2000&normed=true&timecourse_pk__in=49__50&page=1
WARNING:root:Calculating choices

*** study_sid ***
['PKDB99999']
*** study_name ***
['Test1']
*** group_name ***
['all']
*** measurement_type ***
['age', 'healthy', 'overnight fast', 'smoking', 'species']
*** choice ***
['N', 'Y', 'homo sapiens']
*** substance ***
['None']
*** unit ***
['yr']

In [159]:
print("groups")
display(data.groups)
print("individuals")
display(data.individuals)
print("interventions")
display(data.interventions)
print("outputs")
display(data.outputs)
print("timecourses")
display(data.timecourses)

groups

,study_sid,study_name,group_pk,group_name,group_count,group_parent_pk,characteristica_pk,count,measurement_type,choice,substance,value,mean,median,min,max,sd,se,cv,unit
0,PKDB99999,Test1,14,all,6,-1,419,6,species,homo sapiens,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
1,PKDB99999,Test1,14,all,6,-1,420,6,healthy,Y,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
2,PKDB99999,Test1,14,all,6,-1,421,1,smoking,Y,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
3,PKDB99999,Test1,14,all,6,-1,422,5,smoking,N,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
4,PKDB99999,Test1,14,all,6,-1,423,6,age,None,None,NaN,NaN,NaN,25.0,37.0,NaN,NaN,NaN,yr
5,PKDB99999,Test1,14,all,6,-1,424,6,overnight fast,Y,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None

individuals

,study_sid,study_name,individual_pk,individual_name,individual_group_pk,characteristica_pk,count,measurement_type,choice,substance,value,mean,median,min,max,sd,se,cv,unit
0,PKDB99999,Test1,69,TF,14,436,1,age,None,None,27.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yr
1,PKDB99999,Test1,69,TF,14,435,1,weight,None,None,63.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,kilogram
2,PKDB99999,Test1,69,TF,14,424,6,overnight fast,Y,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
3,PKDB99999,Test1,69,TF,14,422,5,smoking,N,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
4,PKDB99999,Test1,69,TF,14,421,1,smoking,Y,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
5,PKDB99999,Test1,69,TF,14,420,6,healthy,Y,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
6,PKDB99999,Test1,69,TF,14,419,6,species,homo sapiens,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
7,PKDB99999,Test1,72,GZ,14,447,1,weight,None,None,79.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,kilogram
8,PKDB99999,Test1,72,GZ,14,424,6,overnight fast,Y,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
9,PKDB99999,Test1,72,GZ,14,422,5,smoking,N,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
10,PKDB99999,Test1,72,GZ,14,421,1,smoking,Y,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
11,PKDB99999,Test1,72,GZ,14,420,6,healthy,Y,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
12,PKDB99999,Test1,72,GZ,14,419,6,species,homo sapiens,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
13,PKDB99999,Test1,72,GZ,14,448,1,age,None,None,29.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yr
14,PKDB99999,Test1,70,UK,14,440,1,age,None,None,37.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yr
15,PKDB99999,Test1,70,UK,14,439,1,weight,None,None,67.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,kilogram
16,PKDB99999,Test1,70,UK,14,424,6,overnight fast,Y,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
17,PKDB99999,Test1,70,UK,14,422,5,smoking,N,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
18,PKDB99999,Test1,70,UK,14,421,1,smoking,Y,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
19,PKDB99999,Test1,70,UK,14,420,6,healthy,Y,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
20,PKDB99999,Test1,70,UK,14,419,6,species,homo sapiens,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
21,PKDB99999,Test1,71,FS,14,444,1,age,None,None,29.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yr
22,PKDB99999,Test1,71,FS,14,443,1,weight,None,None,78.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,kilogram
23,PKDB99999,Test1,71,FS,14,424,6,overnight fast,Y,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
24,PKDB99999,Test1,71,FS,14,422,5,smoking,N,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
25,PKDB99999,Test1,71,FS,14,421,1,smoking,Y,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
26,PKDB99999,Test1,71,FS,14,420,6,healthy,Y,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
27,PKDB99999,Test1,71,FS,14,419,6,species,homo sapiens,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
28,PKDB99999,Test1,67,WS,14,428,1,age,None,None,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yr
29,PKDB99999,Test1,67,WS,14,427,1,weight,None,None,74.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,kilogram
30,PKDB99999,Test1,67,WS,14,424,6,overnight fast,Y,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
31,PKDB99999,Test1,67,WS,14,422,5,smoking,N,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
32,PKDB99999,Test1,67,WS,14,421,1,smoking,Y,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
33,PKDB99999,Test1,67,WS,14,420,6,healthy,Y,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
34,PKDB99999,Test1,67,WS,14,419,6,species,homo sapiens,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
35,PKDB99999,Test1,68,HA,14,432,1,age,None,None,32.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yr
36,PKDB99999,Test1,68,HA,14,431,1,weight,None,None,59.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,kilogram
37,PKDB99999,Test1,68,HA,14,424,6,overnight fast,Y,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
38,PKDB99999,Test1,68,HA,14,422,5,smoking,N,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
39,PKDB99999,Test1,68,HA,14,421,1,smoking,Y,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
40,PKDB99999,Test1,68,HA,14,420,6,healthy,Y,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
41,PKDB99999,Test1,68,HA,14,419,6,species,homo sapiens,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None

interventions

,study_sid,study_name,pk,raw_pk,normed,name,route,form,application,time,...,substance,value,mean,median,min,max,sd,se,cv,unit
0,PKDB99999,Test1,89,87,True,po75,oral,tablet,single dose,0.0,...,midazolam,0.007500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gram
1,PKDB99999,Test1,90,88,True,po15,oral,tablet,single dose,0.0,...,midazolam,0.015000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gram
2,PKDB99999,Test1,92,91,True,iv,iv,solution,single dose,0.0,...,midazolam,0.000075,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gram / kilogram

outputs

,study_sid,study_name,output_pk,intervention_pk,group_pk,individual_pk,normed,calculated,tissue,time,...,substance,value,mean,median,min,max,sd,se,cv,unit
0,PKDB99999,Test1,1944,92,14,-1,True,True,plasma,NaN,...,midazolam,NaN,1.8600,NaN,NaN,NaN,NaN,NaN,NaN,hour
1,PKDB99999,Test1,1943,92,14,-1,True,True,plasma,NaN,...,midazolam,NaN,0.0062,NaN,NaN,NaN,NaN,NaN,NaN,1 / minute
2,PKDB99999,Test1,1920,92,14,-1,True,False,plasma,NaN,...,midazolam,NaN,2.4000,NaN,NaN,NaN,0.8,0.327,0.333,hour
3,PKDB99999,Test1,1901,92,-1,72,True,False,plasma,NaN,...,midazolam,465.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,liter / hour
4,PKDB99999,Test1,1879,92,-1,70,True,False,plasma,NaN,...,midazolam,35.90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,liter / hour
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,PKDB99999,Test1,1837,90,-1,67,True,False,plasma,NaN,...,midazolam,1.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hour
101,PKDB99999,Test1,1875,89,-1,69,True,False,plasma,NaN,...,midazolam,0.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dimensionless
102,PKDB99999,Test1,1873,89,-1,69,True,False,plasma,NaN,...,midazolam,1.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hour
103,PKDB99999,Test1,1870,89,-1,69,True,False,plasma,NaN,...,midazolam,0.08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hour
104,PKDB99999,Test1,1846,89,-1,67,True,False,plasma,NaN,...,midazolam,45.70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,liter / hour

timecourses

,study_sid,study_name,timecourse_pk,intervention_pk,group_pk,individual_pk,normed,tissue,time,time_unit,...,substance,value,mean,median,min,max,sd,se,cv,unit
0,PKDB99999,Test1,49,92,14,-1,True,plasma,"[0.00e+00, 1.70e-01, 3.30e-01, 5.00e-01, 7.50e...",hr,...,midazolam,None,"[1.85e-04, 1.44e-04, 1.21e-04, 1.06e-04, 8.38e...",None,None,None,"[2.33e-05, 1.82e-05, 2.06e-05, 2.68e-05, 1.03e...","[9.52e-06, 7.42e-06, 8.40e-06, 1.09e-05, 4.19e...","[1.26e-01, 1.26e-01, 1.71e-01, 2.53e-01, 1.23e...",gram / liter
1,PKDB99999,Test1,50,90,14,-1,True,plasma,"[1.70e-01, 3.30e-01, 7.50e-01, 1.00e+00, 1.50e...",hr,...,midazolam,None,"[1.01e-05, 1.32e-04, 1.34e-04, 9.67e-05, 9.66e...",None,None,None,"[4.76e-06, 7.49e-05, 3.01e-05, 4.23e-05, 5.29e...","[1.94e-06, 3.06e-05, 1.23e-05, 1.73e-05, 2.16e...","[4.71e-01, 5.66e-01, 2.24e-01, 4.37e-01, 5.48e...",gram / liter

# Example queries

## 1. Query study

In [160]:
pkfilter = PKFilterFactory.by_study_name("Test1")
data = PKData.from_db(pkfilter=pkfilter)

pkfilter = PKFilterFactory.by_study_sid("PKDB99999")
data = PKData.from_db(pkfilter=pkfilter)

WARNING:root:*** Querying data ***
WARNING:root:http://0.0.0.0:8000/api/v1/interventions_elastic/?format=json&page_size=2000&normed=true&study_name=Test1
WARNING:root:http://0.0.0.0:8000/api/v1/interventions_elastic/?format=json&page_size=2000&normed=true&study_name=Test1&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_individuals/?format=json&page_size=2000&study_name=Test1
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_individuals/?format=json&page_size=2000&study_name=Test1&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_groups/?format=json&page_size=2000&study_name=Test1
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_groups/?format=json&page_size=2000&study_name=Test1&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true&study_name=Test1
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true&study_name=Test1&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/timecourse_intervention/?format=json&page_size=2000&normed=true&study_name=Test1
WARNING:root:http://0.0.0.0:8000/api/v1/timecourse_intervention/?format=json&page_size=2000&normed=true&study_name=Test1&page=1
WARNING:root:Calculating choices
WARNING:root:Consice DataFrames
WARNING:root:*** Querying data ***
WARNING:root:http://0.0.0.0:8000/api/v1/interventions_elastic/?format=json&page_size=2000&normed=true&pk__in=89__90__92
WARNING:root:http://0.0.0.0:8000/api/v1/interventions_elastic/?format=json&page_size=2000&normed=true&pk__in=89__90__92&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_individuals/?format=json&page_size=2000&individual_pk__in=69__72__70__71__67__68
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_individuals/?format=json&page_size=2000&individual_pk__in=69__72__70__71__67__68&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_groups/?format=json&page_size=2000&group_pk__in=14
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_groups/?format=json&page_size=2000&group_pk__in=14&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true&output_pk__in=1944__1943__1920__1901__1879__1876__1863__1862__1860__1852__1961__1957__1907__1903__1894__1886__1885__1884__1865__1864__1854__1838__1836__1845__1900__1899__1880__1878__1850__1849__1831__1959__1908__1905__1896__1883__1881__1867__1853__1872__1847__1945__1942__1922__1921__1898__1891__1888__1887__1877__1835__1956__1929__1928__1927__1897__1869__1857__1856__1871__1844__1946__1941__1923__1902__1834__1962__1960__1955__1926__1925__1906__1895__1868__1855__1874__1843__1842__1940__1939__1924__1890__1889__1861__1859__1851__1848__1833__1832__1958__1930__1904__1893__1892__1882__1866__1858__1841__1840__1839__1837__1875__1873__1870__1846
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true&output_pk__in=1944__1943__1920__1901__1879__1876__1863__1862__1860__1852__1961__1957__1907__1903__1894__1886__1885__1884__1865__1864__1854__1838__1836__1845__1900__1899__1880__1878__1850__1849__1831__1959__1908__1905__1896__1883__1881__1867__1853__1872__1847__1945__1942__1922__1921__1898__1891__1888__1887__1877__1835__1956__1929__1928__1927__1897__1869__1857__1856__1871__1844__1946__1941__1923__1902__1834__1962__1960__1955__1926__1925__1906__1895__1868__1855__1874__1843__1842__1940__1939__1924__1890__1889__1861__1859__1851__1848__1833__1832__1958__1930__1904__1893__1892__1882__1866__1858__1841__1840__1839__1837__1875__1873__1870__1846&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/timecourse_intervention/?format=json&page_size=2000&normed=true&timecourse_pk__in=49__50
WARNING:root:http://0.0.0.0:8000/api/v1/timecourse_intervention/?format=json&page_size=2000&normed=true&timecourse_pk__in=49__50&page=1
WARNING:root:Calculating choices
WARNING:root:*** Querying data ***
WARNING:root:http://0.0.0.0:8000/api/v1/interventions_elastic/?format=json&page_size=2000&normed=true&study_sid=PKDB99999
WARNING:root:http://0.0.0.0:8000/api/v1/interventions_elastic/?format=json&page_size=2000&normed=true&study_sid=PKDB99999&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_individuals/?format=json&page_size=2000&study_sid=PKDB99999
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_individuals/?format=json&page_size=2000&study_sid=PKDB99999&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_groups/?format=json&page_size=2000&study_sid=PKDB99999
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_groups/?format=json&page_size=2000&study_sid=PKDB99999&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true&study_sid=PKDB99999
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true&study_sid=PKDB99999&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/timecourse_intervention/?format=json&page_size=2000&normed=true&study_sid=PKDB99999
WARNING:root:http://0.0.0.0:8000/api/v1/timecourse_intervention/?format=json&page_size=2000&normed=true&study_sid=PKDB99999&page=1
WARNING:root:Calculating choices
WARNING:root:Consice DataFrames
WARNING:root:*** Querying data ***
WARNING:root:http://0.0.0.0:8000/api/v1/interventions_elastic/?format=json&page_size=2000&normed=true&pk__in=89__90__92
WARNING:root:http://0.0.0.0:8000/api/v1/interventions_elastic/?format=json&page_size=2000&normed=true&pk__in=89__90__92&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_individuals/?format=json&page_size=2000&individual_pk__in=69__72__70__71__67__68
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_individuals/?format=json&page_size=2000&individual_pk__in=69__72__70__71__67__68&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_groups/?format=json&page_size=2000&group_pk__in=14
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_groups/?format=json&page_size=2000&group_pk__in=14&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true&output_pk__in=1944__1943__1920__1901__1879__1876__1863__1862__1860__1852__1961__1957__1907__1903__1894__1886__1885__1884__1865__1864__1854__1838__1836__1845__1900__1899__1880__1878__1850__1849__1831__1959__1908__1905__1896__1883__1881__1867__1853__1872__1847__1945__1942__1922__1921__1898__1891__1888__1887__1877__1835__1956__1929__1928__1927__1897__1869__1857__1856__1871__1844__1946__1941__1923__1902__1834__1962__1960__1955__1926__1925__1906__1895__1868__1855__1874__1843__1842__1940__1939__1924__1890__1889__1861__1859__1851__1848__1833__1832__1958__1930__1904__1893__1892__1882__1866__1858__1841__1840__1839__1837__1875__1873__1870__1846
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true&output_pk__in=1944__1943__1920__1901__1879__1876__1863__1862__1860__1852__1961__1957__1907__1903__1894__1886__1885__1884__1865__1864__1854__1838__1836__1845__1900__1899__1880__1878__1850__1849__1831__1959__1908__1905__1896__1883__1881__1867__1853__1872__1847__1945__1942__1922__1921__1898__1891__1888__1887__1877__1835__1956__1929__1928__1927__1897__1869__1857__1856__1871__1844__1946__1941__1923__1902__1834__1962__1960__1955__1926__1925__1906__1895__1868__1855__1874__1843__1842__1940__1939__1924__1890__1889__1861__1859__1851__1848__1833__1832__1958__1930__1904__1893__1892__1882__1866__1858__1841__1840__1839__1837__1875__1873__1870__1846&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/timecourse_intervention/?format=json&page_size=2000&normed=true&timecourse_pk__in=49__50
WARNING:root:http://0.0.0.0:8000/api/v1/timecourse_intervention/?format=json&page_size=2000&normed=true&timecourse_pk__in=49__50&page=1
WARNING:root:Calculating choices

## Query groups and individuals
### 2.1 Get data for groups with characteristica/keywords X
healthy=True, smoking=N, disease=None,
individual queries and combinations.

In [176]:
pkfilter_healthy = PKFilter()

measurement_type = "healthy"
choice = "Y"

pkfilter_healthy.groups["measurement_type"] = measurement_type
pkfilter_healthy.groups["choice"] = choice

pkfilter_healthy.individuals["measurement_type"] = measurement_type
pkfilter_healthy.individuals["choice"] = choice

data_healthy = PKData.from_db(pkfilter=pkfilter_healthy)

pkfilter_smoking = PKFilter()

measurement_type = "smoking"
choice = "Y"

pkfilter_smoking.groups["measurement_type"] = measurement_type
pkfilter_smoking.groups["choice"] = choice

pkfilter_smoking.individuals["measurement_type"] = measurement_type
pkfilter_smoking.individuals["choice"] = choice
data_smoking = PKData.from_db(pkfilter=pkfilter_smoking)


pkfilter_disease = PKFilter()

measurement_type = "disease"

pkfilter_disease.groups["measurement_type"] = measurement_type
pkfilter_disease.individuals["measurement_type"] = measurement_type

data_disease = PKData.from_db(pkfilter=pkfilter_disease)

#data_smoking & pkfilter_healthy

WARNING:root:*** Querying data ***
WARNING:root:http://0.0.0.0:8000/api/v1/interventions_elastic/?format=json&page_size=2000&normed=true
WARNING:root:http://0.0.0.0:8000/api/v1/interventions_elastic/?format=json&page_size=2000&normed=true&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_individuals/?format=json&page_size=2000&measurement_type=healthy&choice=Y
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_individuals/?format=json&page_size=2000&measurement_type=healthy&choice=Y&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_groups/?format=json&page_size=2000&measurement_type=healthy&choice=Y
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_groups/?format=json&page_size=2000&measurement_type=healthy&choice=Y&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true&page=2
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true&page=3
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true&page=4
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true&page=5
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true&page=6
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true&page=7
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true&page=8
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true&page=9
WARNING:root:http://0.0.0.0:8000/api/v1/timecourse_intervention/?format=json&page_size=2000&normed=true
WARNING:root:http://0.0.0.0:8000/api/v1/timecourse_intervention/?format=json&page_size=2000&normed=true&page=1
WARNING:root:Calculating choices
WARNING:root:Consice DataFrames
WARNING:root:*** Querying data ***
WARNING:root:http://0.0.0.0:8000/api/v1/interventions_elastic/?format=json&page_size=2000&normed=true&pk__in=152__153__154__155__156__158__221__222__225__226__229__230__121__122__127__128__129__130__233__234__237__238__141__142__144__146__160__164__165__166__132__135__136__138__112__113__114__89__90__92__94__96__320__322__324__302__311__312__307__308__402__401__400__399__466__468__382__384__386__388__390__480__484__486__490__492__478__477__476__488__392__632__634__638__642__644__646__648__650__666__668__608__616__716__718__720__724__726__728__710__712__714__736__735__738__746__722__730__732__898__900__902__904__906__908__860__862__864__866__896__895__894__893__910__912__914__882__884__886__888__916__918__920__868__870__872__874__876__856__858__976__974__972__970__980__978__984__986__966__990__982__988__968__1002__1000__1024__1022__1020__1018__996__994__1016__1014__1026__998__992__175__189__283__284__291__292__293__294__295__296__274__276__279__280__241__242__244__251__254__266__268__270__298__256__259__260__246__248__262__264__374__376__378__380__328__330__332__364__366__368__370__372__344__510__509__508__507__520__519__518__517__516__540__542__500__502__494__576__583__584__585__586__587__588__590__544__546__548__554__556__558__592__594__596__598__550__552__600__574__688__690__692__694__704__700__708__696__686__698__810__809__808__807__820__819__816__830__829__826__840__836__850__849__846__776__778__780__782__784__786__788__790__792__794__796__798__800__802__766__770__752__754__756__758__764__763__762__852__854__748__750__772__774__936__938__940__942__952__950__948__946__944__922__924__926__958__956__954__932__934__928__930__960__962__964__1031__1028__1036__1040__1042__1046__1044__1048__1050
WARNING:root:http://0.0.0.0:8000/api/v1/interventions_elastic/?format=json&page_size=2000&normed=true&pk__in=152__153__154__155__156__158__221__222__225__226__229__230__121__122__127__128__129__130__233__234__237__238__141__142__144__146__160__164__165__166__132__135__136__138__112__113__114__89__90__92__94__96__320__322__324__302__311__312__307__308__402__401__400__399__466__468__382__384__386__388__390__480__484__486__490__492__478__477__476__488__392__632__634__638__642__644__646__648__650__666__668__608__616__716__718__720__724__726__728__710__712__714__736__735__738__746__722__730__732__898__900__902__904__906__908__860__862__864__866__896__895__894__893__910__912__914__882__884__886__888__916__918__920__868__870__872__874__876__856__858__976__974__972__970__980__978__984__986__966__990__982__988__968__1002__1000__1024__1022__1020__1018__996__994__1016__1014__1026__998__992__175__189__283__284__291__292__293__294__295__296__274__276__279__280__241__242__244__251__254__266__268__270__298__256__259__260__246__248__262__264__374__376__378__380__328__330__332__364__366__368__370__372__344__510__509__508__507__520__519__518__517__516__540__542__500__502__494__576__583__584__585__586__587__588__590__544__546__548__554__556__558__592__594__596__598__550__552__600__574__688__690__692__694__704__700__708__696__686__698__810__809__808__807__820__819__816__830__829__826__840__836__850__849__846__776__778__780__782__784__786__788__790__792__794__796__798__800__802__766__770__752__754__756__758__764__763__762__852__854__748__750__772__774__936__938__940__942__952__950__948__946__944__922__924__926__958__956__954__932__934__928__930__960__962__964__1031__1028__1036__1040__1042__1046__1044__1048__1050&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_individuals/?format=json&page_size=2000&individual_pk__in=309__323__327__320__321__316__312__324__310__319__318__325__314__317__308__322__313__315__326__311__81__77__76__74__82__79__75__80__78__73__86__84__85__83__91__92__90__93__89__87__94__88__280__283__284__287__285__286__282__281__273__267__272__257__279__258__275__260__278__274__254__276__259__252__262__250__253__271__263__256__277__268__251__265__266__264__255__270__269__261__191__193__189__194__190__192__305__302__307__306__304__303__69__72__70__71__67__68__662__677__641__653__665__638__640__635__674__625__630__623__667__668__639__629__624__652__655__636__627__659__637__645__676__634__633__632__658__673__649__651__664__631__666__643__650__647__656__670__678__642__669__644__646__672__660__648__622__657__663__626__661__671__654__628__675__708__713__712__707__711__714__710__709__704__706__703__705__749__1037__1081__970__1002__1091__1023__1009__1075__959__1092__1050__1095__1034__996__1056__1063__1059__1044__1003__1045__971__1062__967__983__957__976__1052__1065__1067__998__1042__1096__999__1064__961__1036__982__1079__988__1018__1085__964__1057__1094__990__1022__1046__1031__1066__1090__973__1069__989__1004__1016__1041__1043__1015__965__1088__954__1038__1027__1089__1024__1070__981__1001__1021__1077__1032__960__997__1029__1030__1068__1028__984__1000__992__972__978__1084__1020__974__1060__980__1039__956__958__1017__806__834__811__831__813__841__846__809__828__814__820__803__807__850__839__837__861__844__853__858__819__829__817__826__804__854__822__823__799__801__855__833__848__849__863__862__818__836__851__830__838__821__805__816__808__856__860__845__847__802__815__827__843__842__859__812__835__864__824__852__840__825__857__832__800__810__786__789__753__765__773__781__788__761__758__785__797__783__762__751__776__752__770__754__782__793__764__784__759__780__768__798__775__791__772__763__778__792__756__755__757__771__777__794__767__766__760__787__750__769__779__774__796__795__790__955__963__1071__991__1058__1025__1051__975__1007__1013__1086__953__1076__1093__968__1053__1097__979__1048__993__1035__1073__1078__1047__1019__1049__1054__1083__1011__1006__1008__1072__1005__1080__952__1012__1033__966__987__994__1087__1055__1026__986__995__1040__1061__1014__985__1074__962__969__977__1010__1082__906__908__909__910__907__904__905__912__911__1102__1098__1103__1099__1100__1101__1474__1526__1489__1521__1439__1528__1491__1437__1453__1531__1460__1472__1506__1509__1494__1523__1517__1466__1471__1458__1504__1493__1514__1535__1475__1536__1433__1482__1488__1445__1492__1462__1456__1483__1438__1447__1426__1485__1467__1431__1534__1480__1481__1490__1444__1422__1470__1473__1425__1532__1519__1440__1540__1527__1434__1533__1448__1510__1520__1501__1479__1495__1463__1468__1436__1469__1516__1464__1486__1461__1525__1429__1443__1427__1455__1524__1484__1518__1508__1496__1364__1362__1363__1398__1407__1393__1396__1403__1395__1406__1401__1402__1399__1397__1394__1405__1404__1408__1400__1384__1388__1389__1387__1377__1381__1375__1379__1386__1390__1391__1383__1378__1376__1380__1382__1373__1385__1374__1392__1423__1446__1430__1419__1538__1487__1477__1424__1428__1512__1432__1513__1505__1529__1530__1452__1441__1418__1511__1522__1442__1450__1476__1459__1449__1497__1435__1537__1451__1498__1499__1539__1457__1454__1500__1503__1515__1420__1507__1421__1502__1465__1478__1409__1410__1411__1412__1414__1415__1416__1413__1417__1543__1544__1541__1554__1546__1551__1542__1548__1552__1553__1550__1545__1547__1549__1555__1556__1560__1559__1557__1562__1563__1558__1561__438__436__437__184__116__179__138__181__146__162__105__132__174__107__134__144__170__176__169__168__163__175__180__115__114__167__112__109__108__158__156__155__135__118__133__111__127__124__123__128__126__173__149__166__103__161__142__121__117__188__152__125__119__113__153__157__147__183__120__136__150__140__139__187__164__137__160__159__172__141__122__186__154__131__177__182__106__104__185__110__171__178__145__148__130__129__165__143__151__494__499__517__487__475__493__488__482__489__500__515__496__486__478__505__502__485__476__490__492__477__481__507__480__511__516__514__483__472__484__503__479__491__510__513__473__495__509__504__506__508__501__474__512__498__497__559__561__552__554__558__553__560__556__555__557__439__434__435__581__1159__1168__1260__1203__1250__1176__1186__1116__1290__1147__1334__1221__1227__1126__1280__1295__1233__1346__1164__1256__1217__1298__1267__1249__1335__1245__1211__1305__1344__1229__1326__1230__1127__1294__1114__1297__1337__1304__1345__1121__1177__1213__1319__1266__1343__1311__1286__1134__1137__1153__1323__1222__1237__1190__1321__1264__1309__1142__1216__1178__1140__1279__1324__1291__1154__1325__1212__1214__1332__1341__1347__1246__1206__1200__1231__1276__1117__1251__1189__1310__1181__1315__1135__1156__1205__1172__1198__1208__1351__1183__1349__1333__1234__1195__1174__1197__1259__1220__1242__1299__1160__1338__1167__1202__1285__1144__1152__1330__1340__1132__1141__1329__1336__1170__1130__1155__1145__1158__1269__1300__1277__1128__1284__1274__1226__1187__1136__1123__1317__1272__1248__1331__1219__1307__1348__1273__1175__1268__1193__1235__1204__1301__1169__1171__1252__1138__1236__1263__1255__1122__1308__1322__1166__1224__1241__1302__1293__1209__1244__1303__1151__1292__1207__1288__1185__1254__1265__1133__1180__1318__1271__1146__1215__1210__1139__1327__1223__1225__1240__1342__1238__1296__1182__1120__1257__1283__1188__1306__1320__1282__1191__1258__1328__1184__1289__1161__1129__1313__1150__1192__1124__1119__1218__1243__1262__1194__1143__1165__1270__1287__1162__1281__1247__1232__1239__1228__1312__1173__1261__1201__1314__1196__1149__1163__1148__1278__1115__1118__1199__1316__1350__1131__1125__1179__1253__1275__1339__1157__1112__1113__1111__1608__1605__1614__1613__1616__1620__1623__1606__1622__1617__1610__1619__1621__1611__1615__1607__1612__1618__1624__1609__1642__1638__1641__1640__1639__1654__1651__1655__1653__1656__1657__1658__1665__1660__1662__1663__1661__1666__1664__1659__1648__1646__1649__1647__1645__1650__1643__1644__1629__1630__1632__1631__1627__1628__1625__1626__1775__1798__1826__1791__1800__1810__1822__1774__1779__1818__1817__1786__1809__1804__1801__1807__1819__1787__1816__1778__1799__1794__1797__1792__1805__1788__1808__1790__1802__1815__1824__1825__1789__1814__1823__1827__1777__1796__1812__1795__1784__1811__1776__1782__1803__1793__1780__1821__1785__1783__1820__1781__1806__1813__1698__1699__1725__1692__1703__1719__1705__1716__1715__1697__1709__1700__1710__1718__1721__1726__1714__1706__1694__1704__1712__1723__1690__1713__1701__1693__1722__1833__1828__1834__1836__1831__1837__1835__1829__1832__1830__1669__1667__1671__1670__1675__1674__1673__1668__1672__1724__1702__1707__1717__1685__1688__1682__1680__1681__1687__1676__1683__1684__1686__1689__1679__1677__1678__1744__1742__1747__1748__1743__1741__1753__1750__1754__1740__1739__1746__1749__1738__1745__1737__1751__1752__1695__1711__1727__1691__1708__1720__1696__1764__1758__1756__1761__1755__1759__1763__1760__1757__1762__1855__1861__1856__1851__1849__1854__1857__1848__1860__1862__1859__1852__1858__1853__1850__1863__1889__1870__1898__1890__1899__1891__1876__1913__1869__1885__1914__1904__1933__1930__1877__1903__1892__1880__1912__1905__1886__1882__1883__1871__1897__1919__1894__1922__1921__1901__1884__1874__1920__1879__1872__1928__1887__1924__1931__1866__1878__1909__1932__1908__1864__1881__1865__1895__1911__1925__1888__1906__1918__1917__1875__1868__1915__1916__1927__1929__1902__1867__1893__1873__1910__1926__1923__1900__1896__1907__1939__1945__1935__1943__1940__1941__1934__1938__1944__1937__1936__1942

HTTPError: 500 Server Error: Internal Server Error for url: http://0.0.0.0:8000/api/v1/characteristica_individuals/?format=json&page_size=2000&individual_pk__in=309__323__327__320__321__316__312__324__310__319__318__325__314__317__308__322__313__315__326__311__81__77__76__74__82__79__75__80__78__73__86__84__85__83__91__92__90__93__89__87__94__88__280__283__284__287__285__286__282__281__273__267__272__257__279__258__275__260__278__274__254__276__259__252__262__250__253__271__263__256__277__268__251__265__266__264__255__270__269__261__191__193__189__194__190__192__305__302__307__306__304__303__69__72__70__71__67__68__662__677__641__653__665__638__640__635__674__625__630__623__667__668__639__629__624__652__655__636__627__659__637__645__676__634__633__632__658__673__649__651__664__631__666__643__650__647__656__670__678__642__669__644__646__672__660__648__622__657__663__626__661__671__654__628__675__708__713__712__707__711__714__710__709__704__706__703__705__749__1037__1081__970__1002__1091__1023__1009__1075__959__1092__1050__1095__1034__996__1056__1063__1059__1044__1003__1045__971__1062__967__983__957__976__1052__1065__1067__998__1042__1096__999__1064__961__1036__982__1079__988__1018__1085__964__1057__1094__990__1022__1046__1031__1066__1090__973__1069__989__1004__1016__1041__1043__1015__965__1088__954__1038__1027__1089__1024__1070__981__1001__1021__1077__1032__960__997__1029__1030__1068__1028__984__1000__992__972__978__1084__1020__974__1060__980__1039__956__958__1017__806__834__811__831__813__841__846__809__828__814__820__803__807__850__839__837__861__844__853__858__819__829__817__826__804__854__822__823__799__801__855__833__848__849__863__862__818__836__851__830__838__821__805__816__808__856__860__845__847__802__815__827__843__842__859__812__835__864__824__852__840__825__857__832__800__810__786__789__753__765__773__781__788__761__758__785__797__783__762__751__776__752__770__754__782__793__764__784__759__780__768__798__775__791__772__763__778__792__756__755__757__771__777__794__767__766__760__787__750__769__779__774__796__795__790__955__963__1071__991__1058__1025__1051__975__1007__1013__1086__953__1076__1093__968__1053__1097__979__1048__993__1035__1073__1078__1047__1019__1049__1054__1083__1011__1006__1008__1072__1005__1080__952__1012__1033__966__987__994__1087__1055__1026__986__995__1040__1061__1014__985__1074__962__969__977__1010__1082__906__908__909__910__907__904__905__912__911__1102__1098__1103__1099__1100__1101__1474__1526__1489__1521__1439__1528__1491__1437__1453__1531__1460__1472__1506__1509__1494__1523__1517__1466__1471__1458__1504__1493__1514__1535__1475__1536__1433__1482__1488__1445__1492__1462__1456__1483__1438__1447__1426__1485__1467__1431__1534__1480__1481__1490__1444__1422__1470__1473__1425__1532__1519__1440__1540__1527__1434__1533__1448__1510__1520__1501__1479__1495__1463__1468__1436__1469__1516__1464__1486__1461__1525__1429__1443__1427__1455__1524__1484__1518__1508__1496__1364__1362__1363__1398__1407__1393__1396__1403__1395__1406__1401__1402__1399__1397__1394__1405__1404__1408__1400__1384__1388__1389__1387__1377__1381__1375__1379__1386__1390__1391__1383__1378__1376__1380__1382__1373__1385__1374__1392__1423__1446__1430__1419__1538__1487__1477__1424__1428__1512__1432__1513__1505__1529__1530__1452__1441__1418__1511__1522__1442__1450__1476__1459__1449__1497__1435__1537__1451__1498__1499__1539__1457__1454__1500__1503__1515__1420__1507__1421__1502__1465__1478__1409__1410__1411__1412__1414__1415__1416__1413__1417__1543__1544__1541__1554__1546__1551__1542__1548__1552__1553__1550__1545__1547__1549__1555__1556__1560__1559__1557__1562__1563__1558__1561__438__436__437__184__116__179__138__181__146__162__105__132__174__107__134__144__170__176__169__168__163__175__180__115__114__167__112__109__108__158__156__155__135__118__133__111__127__124__123__128__126__173__149__166__103__161__142__121__117__188__152__125__119__113__153__157__147__183__120__136__150__140__139__187__164__137__160__159__172__141__122__186__154__131__177__182__106__104__185__110__171__178__145__148__130__129__165__143__151__494__499__517__487__475__493__488__482__489__500__515__496__486__478__505__502__485__476__490__492__477__481__507__480__511__516__514__483__472__484__503__479__491__510__513__473__495__509__504__506__508__501__474__512__498__497__559__561__552__554__558__553__560__556__555__557__439__434__435__581__1159__1168__1260__1203__1250__1176__1186__1116__1290__1147__1334__1221__1227__1126__1280__1295__1233__1346__1164__1256__1217__1298__1267__1249__1335__1245__1211__1305__1344__1229__1326__1230__1127__1294__1114__1297__1337__1304__1345__1121__1177__1213__1319__1266__1343__1311__1286__1134__1137__1153__1323__1222__1237__1190__1321__1264__1309__1142__1216__1178__1140__1279__1324__1291__1154__1325__1212__1214__1332__1341__1347__1246__1206__1200__1231__1276__1117__1251__1189__1310__1181__1315__1135__1156__1205__1172__1198__1208__1351__1183__1349__1333__1234__1195__1174__1197__1259__1220__1242__1299__1160__1338__1167__1202__1285__1144__1152__1330__1340__1132__1141__1329__1336__1170__1130__1155__1145__1158__1269__1300__1277__1128__1284__1274__1226__1187__1136__1123__1317__1272__1248__1331__1219__1307__1348__1273__1175__1268__1193__1235__1204__1301__1169__1171__1252__1138__1236__1263__1255__1122__1308__1322__1166__1224__1241__1302__1293__1209__1244__1303__1151__1292__1207__1288__1185__1254__1265__1133__1180__1318__1271__1146__1215__1210__1139__1327__1223__1225__1240__1342__1238__1296__1182__1120__1257__1283__1188__1306__1320__1282__1191__1258__1328__1184__1289__1161__1129__1313__1150__1192__1124__1119__1218__1243__1262__1194__1143__1165__1270__1287__1162__1281__1247__1232__1239__1228__1312__1173__1261__1201__1314__1196__1149__1163__1148__1278__1115__1118__1199__1316__1350__1131__1125__1179__1253__1275__1339__1157__1112__1113__1111__1608__1605__1614__1613__1616__1620__1623__1606__1622__1617__1610__1619__1621__1611__1615__1607__1612__1618__1624__1609__1642__1638__1641__1640__1639__1654__1651__1655__1653__1656__1657__1658__1665__1660__1662__1663__1661__1666__1664__1659__1648__1646__1649__1647__1645__1650__1643__1644__1629__1630__1632__1631__1627__1628__1625__1626__1775__1798__1826__1791__1800__1810__1822__1774__1779__1818__1817__1786__1809__1804__1801__1807__1819__1787__1816__1778__1799__1794__1797__1792__1805__1788__1808__1790__1802__1815__1824__1825__1789__1814__1823__1827__1777__1796__1812__1795__1784__1811__1776__1782__1803__1793__1780__1821__1785__1783__1820__1781__1806__1813__1698__1699__1725__1692__1703__1719__1705__1716__1715__1697__1709__1700__1710__1718__1721__1726__1714__1706__1694__1704__1712__1723__1690__1713__1701__1693__1722__1833__1828__1834__1836__1831__1837__1835__1829__1832__1830__1669__1667__1671__1670__1675__1674__1673__1668__1672__1724__1702__1707__1717__1685__1688__1682__1680__1681__1687__1676__1683__1684__1686__1689__1679__1677__1678__1744__1742__1747__1748__1743__1741__1753__1750__1754__1740__1739__1746__1749__1738__1745__1737__1751__1752__1695__1711__1727__1691__1708__1720__1696__1764__1758__1756__1761__1755__1759__1763__1760__1757__1762__1855__1861__1856__1851__1849__1854__1857__1848__1860__1862__1859__1852__1858__1853__1850__1863__1889__1870__1898__1890__1899__1891__1876__1913__1869__1885__1914__1904__1933__1930__1877__1903__1892__1880__1912__1905__1886__1882__1883__1871__1897__1919__1894__1922__1921__1901__1884__1874__1920__1879__1872__1928__1887__1924__1931__1866__1878__1909__1932__1908__1864__1881__1865__1895__1911__1925__1888__1906__1918__1917__1875__1868__1915__1916__1927__1929__1902__1867__1893__1873__1910__1926__1923__1900__1896__1907__1939__1945__1935__1943__1940__1941__1934__1938__1944__1937__1936__1942

In [167]:
measurement_type = "disease"
pkfilter_disease.groups["measurement_type"] = measurement_type
pkfilter_disease.individuals["measurement_type"] = measurement_type
data_disease = PKData.from_db(pkfilter=pkfilter_disease)

WARNING:root:*** Querying data ***
WARNING:root:http://0.0.0.0:8000/api/v1/interventions_elastic/?format=json&page_size=2000&normed=true
WARNING:root:http://0.0.0.0:8000/api/v1/interventions_elastic/?format=json&page_size=2000&normed=true&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_individuals/?format=json&page_size=2000&measurement_type=disease
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_individuals/?format=json&page_size=2000&measurement_type=disease&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_groups/?format=json&page_size=2000&measurement_type=disease
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_groups/?format=json&page_size=2000&measurement_type=disease&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true&page=2
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true&page=3
WARNING:root:http://0.0.0.0:8000/api/v1/timecourse_intervention/?format=json&page_size=2000&normed=true
WARNING:root:http://0.0.0.0:8000/api/v1/timecourse_intervention/?format=json&page_size=2000&normed=true&page=1
WARNING:root:Calculating choices
WARNING:root:Consice DataFrames
WARNING:root:*** Querying data ***
WARNING:root:http://0.0.0.0:8000/api/v1/interventions_elastic/?format=json&page_size=2000&normed=true&pk__in=304__172__246__248
WARNING:root:http://0.0.0.0:8000/api/v1/interventions_elastic/?format=json&page_size=2000&normed=true&pk__in=304__172__246__248&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_individuals/?format=json&page_size=2000&individual_pk__in=563__577__567__575__568__574__562__572__571__565__578__566__564__579__576__573__570__580__569
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_individuals/?format=json&page_size=2000&individual_pk__in=563__577__567__575__568__574__562__572__571__565__578__566__564__579__576__573__570__580__569&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_groups/?format=json&page_size=2000&group_pk__in=49__105__104__68
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_groups/?format=json&page_size=2000&group_pk__in=49__105__104__68&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true&output_pk__in=3911__4893__4891__4888__4887__7004__6983__6956__6955__6953__6952__6950__6944__6941__6940__6934__6928__6927__6924__6908__6907__6906__6905__6903__3910__7003__6985__6984__6954__6948__6947__6945__6943__6933__6929__6923__6920__6918__6917__6910__6909__4861__4860__4857__4825__4824__3916__3915__6987__6986__6942__6939__6937__6930__6926__6921__6914__6904__6902__6901__4862__4859__4858__4826__3914__3913__3912__4856__4823__4894__4890__7002__7001__6999__6982__6949__6946__6931__6925__6919__6916__7000__6998__6997__6988__6981__6951__6938__6936__6935__6932__6922__6915__6913__6912__6911__6900__4855__4892__4889
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true&output_pk__in=3911__4893__4891__4888__4887__7004__6983__6956__6955__6953__6952__6950__6944__6941__6940__6934__6928__6927__6924__6908__6907__6906__6905__6903__3910__7003__6985__6984__6954__6948__6947__6945__6943__6933__6929__6923__6920__6918__6917__6910__6909__4861__4860__4857__4825__4824__3916__3915__6987__6986__6942__6939__6937__6930__6926__6921__6914__6904__6902__6901__4862__4859__4858__4826__3914__3913__3912__4856__4823__4894__4890__7002__7001__6999__6982__6949__6946__6931__6925__6919__6916__7000__6998__6997__6988__6981__6951__6938__6936__6935__6932__6922__6915__6913__6912__6911__6900__4855__4892__4889&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/timecourse_intervention/?format=json&page_size=2000&normed=true&timecourse_pk__in=328__327__224__226
WARNING:root:http://0.0.0.0:8000/api/v1/timecourse_intervention/?format=json&page_size=2000&normed=true&timecourse_pk__in=328__327__224__226&page=1
WARNING:root:Calculating choices

WARNING:root:*** Querying data ***
WARNING:root:http://0.0.0.0:8000/api/v1/interventions_elastic/?format=json&page_size=2000&normed=true&pk__in=304__172__246__248
WARNING:root:http://0.0.0.0:8000/api/v1/interventions_elastic/?format=json&page_size=2000&normed=true&pk__in=304__172__246__248&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_individuals/?format=json&page_size=2000&individual_pk__in=563__577__567__575__568__574__562__572__571__565__578__566__564__579__576__573__570__580__569
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_individuals/?format=json&page_size=2000&individual_pk__in=563__577__567__575__568__574__562__572__571__565__578__566__564__579__576__573__570__580__569&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_groups/?format=json&page_size=2000&group_pk__in=49__105__104__68
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_groups/?format=json&page_size=2000&group_pk__in=49__105__104__68&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true&output_pk__in=3911__4893__4891__4888__4887__7004__6983__6956__6955__6953__6952__6950__6944__6941__6940__6934__6928__6927__6924__6908__6907__6906__6905__6903__3910__7003__6985__6984__6954__6948__6947__6945__6943__6933__6929__6923__6920__6918__6917__6910__6909__4861__4860__4857__4825__4824__3916__3915__6987__6986__6942__6939__6937__6930__6926__6921__6914__6904__6902__6901__4862__4859__4858__4826__3914__3913__3912__4856__4823__4894__4890__7002__7001__6999__6982__6949__6946__6931__6925__6919__6916__7000__6998__6997__6988__6981__6951__6938__6936__6935__6932__6922__6915__6913__6912__6911__6900__4855__4892__4889
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true&output_pk__in=3911__4893__4891__4888__4887__7004__6983__6956__6955__6953__6952__6950__6944__6941__6940__6934__6928__6927__6924__6908__6907__6906__6905__6903__3910__7003__6985__6984__6954__6948__6947__6945__6943__6933__6929__6923__6920__6918__6917__6910__6909__4861__4860__4857__4825__4824__3916__3915__6987__6986__6942__6939__6937__6930__6926__6921__6914__6904__6902__6901__4862__4859__4858__4826__3914__3913__3912__4856__4823__4894__4890__7002__7001__6999__6982__6949__6946__6931__6925__6919__6916__7000__6998__6997__6988__6981__6951__6938__6936__6935__6932__6922__6915__6913__6912__6911__6900__4855__4892__4889&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/timecourse_intervention/?format=json&page_size=2000&normed=true&timecourse_pk__in=328__327__224__226
WARNING:root:http://0.0.0.0:8000/api/v1/timecourse_intervention/?format=json&page_size=2000&normed=true&timecourse_pk__in=328__327__224__226&page=1
WARNING:root:Calculating choices

In [173]:
d._concise()
d.groups

WARNING:root:Consice DataFrames

,study_sid,study_name,group_pk,group_name,group_count,group_parent_pk,characteristica_pk,count,measurement_type,choice,substance,value,mean,median,min,max,sd,se,cv,unit
0,3161005,Kanto1985,49,4,15,37,912,15,disease,renal disease (end-stage),None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
1,3161005,Kanto1985,49,4,15,37,896,207,species,homo sapiens,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
2,3271619,Adithan1988,105,type II,10,103,1686,29,overnight fast,Y,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
3,3271619,Adithan1988,105,type II,10,103,1685,29,kidney function test,normal,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
4,3271619,Adithan1988,105,type II,10,103,1684,29,liver function test,normal,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
5,3271619,Adithan1988,105,type II,10,103,1683,29,abstinence medication,None,None,NaN,NaN,NaN,30.43685,NaN,NaN,NaN,NaN,day
6,3271619,Adithan1988,105,type II,10,103,1682,29,abstinence alcohol,None,None,NaN,NaN,NaN,30.43685,NaN,NaN,NaN,NaN,day
7,3271619,Adithan1988,105,type II,10,103,1681,29,smoking,N,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
8,3271619,Adithan1988,105,type II,10,103,1680,29,species,homo sapiens,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
9,3271619,Adithan1988,105,type II,10,103,1702,10,disease,t2dm,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
10,3271619,Adithan1988,105,type II,10,103,1701,10,weight,None,None,NaN,57.5,NaN,NaN,NaN,2.2,NaN,NaN,kilogram
11,3271619,Adithan1988,105,type II,10,103,1700,10,age,None,None,NaN,49.1,NaN,NaN,NaN,2.9,NaN,NaN,yr
12,3271619,Adithan1988,104,type I,9,103,1695,9,weight,None,None,NaN,37.8,NaN,NaN,NaN,2.9,NaN,NaN,kilogram
13,3271619,Adithan1988,104,type I,9,103,1694,9,age,None,None,NaN,27.2,NaN,NaN,NaN,3.8,NaN,NaN,yr
14,3271619,Adithan1988,104,type I,9,103,1686,29,overnight fast,Y,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
15,3271619,Adithan1988,104,type I,9,103,1685,29,kidney function test,normal,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
16,3271619,Adithan1988,104,type I,9,103,1684,29,liver function test,normal,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
17,3271619,Adithan1988,104,type I,9,103,1683,29,abstinence medication,None,None,NaN,NaN,NaN,30.43685,NaN,NaN,NaN,NaN,day
18,3271619,Adithan1988,104,type I,9,103,1682,29,abstinence alcohol,None,None,NaN,NaN,NaN,30.43685,NaN,NaN,NaN,NaN,day
19,3271619,Adithan1988,104,type I,9,103,1681,29,smoking,N,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
20,3271619,Adithan1988,104,type I,9,103,1680,29,species,homo sapiens,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
21,3271619,Adithan1988,104,type I,9,103,1696,9,disease,t1dm,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
22,2723115,Pentikaeinen1989,68,patients,7,66,1098,2,smoking,N,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
23,2723115,Pentikaeinen1989,68,patients,7,66,1070,14,body position,supine,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
24,2723115,Pentikaeinen1989,68,patients,7,66,1069,14,overnight fast,Y,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
25,2723115,Pentikaeinen1989,68,patients,7,66,1068,14,abstinence alcohol,None,None,NaN,NaN,NaN,7.00000,NaN,NaN,NaN,NaN,day
26,2723115,Pentikaeinen1989,68,patients,7,66,1067,14,sex,M,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
27,2723115,Pentikaeinen1989,68,patients,7,66,1066,14,species,homo sapiens,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
28,2723115,Pentikaeinen1989,68,patients,7,66,1097,5,smoking,Y,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
29,2723115,Pentikaeinen1989,68,patients,7,66,1096,2,medication,N,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
30,2723115,Pentikaeinen1989,68,patients,7,66,1095,5,medication,Y,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
31,2723115,Pentikaeinen1989,68,patients,7,66,1094,7,weight,None,None,NaN,85.1,NaN,NaN,NaN,12.2,NaN,NaN,kilogram
32,2723115,Pentikaeinen1989,68,patients,7,66,1093,7,age,None,None,NaN,48.0,NaN,NaN,NaN,13.9,NaN,NaN,yr
33,2723115,Pentikaeinen1989,68,patients,7,66,1092,7,disease,liver disease,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
34,2723115,Pentikaeinen1989,68,patients,7,66,1091,7,healthy,N,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None

In [148]:
pkfilter_disease = PKFilter()
data_disease = PKData.from_db(pkfilter=pkfilter_disease)

WARNING:root:*** Querying data ***
WARNING:root:http://0.0.0.0:8000/api/v1/interventions_elastic/?format=json&page_size=2000&normed=true
WARNING:root:http://0.0.0.0:8000/api/v1/interventions_elastic/?format=json&page_size=2000&normed=true&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_individuals/?format=json&page_size=2000
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_individuals/?format=json&page_size=2000&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_groups/?format=json&page_size=2000
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_groups/?format=json&page_size=2000&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true&study_name__exclude=Backman1996
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true&study_name__exclude=Backman1996&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/timecourse_intervention/?format=json&page_size=2000&normed=true
WARNING:root:http://0.0.0.0:8000/api/v1/timecourse_intervention/?format=json&page_size=2000&normed=true&page=1
WARNING:root:Calculating choices

In [150]:
data_disease.outputs["study_name"].unique()

array(['Bornemann1985', 'Farkas2007', 'Test1'], dtype=object)

TODO: implement merge of PKDBData

### 2.2 Get data for individuals with characteristica X
### 2.3 Get data for an exclusion criteria, i.e. NOT diease=None

In [83]:
data.concise()
data.load()

WARNING:root:Consice DataFrames

642

In [110]:
pkfilter_healthy = PKFilter()
pkfilter_healthy.groups["measurement_type"] = "healthy"
pkfilter_healthy.groups["choice"] = "Y"
data_healthy = PKData.from_db(pkfilter=pkfilter_healthy)

pkfilter_smoking = PKFilter()
pkfilter_smoking.groups["measurement_type"] = "smoking"
pkfilter_smoking.groups["choice"] = "Y"
data_smoking = PKData.from_db(pkfilter=pkfilter_smoking)

WARNING:root:*** Querying data ***
WARNING:root:http://0.0.0.0:8000/api/v1/interventions_elastic/?format=json&page_size=2000&normed=true
WARNING:root:http://0.0.0.0:8000/api/v1/interventions_elastic/?format=json&page_size=2000&normed=true&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_individuals/?format=json&page_size=2000
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_individuals/?format=json&page_size=2000&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_groups/?format=json&page_size=2000&measurement_type=healthy&choice=Y
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_groups/?format=json&page_size=2000&measurement_type=healthy&choice=Y&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/timecourse_intervention/?format=json&page_size=2000&normed=true
WARNING:root:http://0.0.0.0:8000/api/v1/timecourse_intervention/?format=json&page_size=2000&normed=true&page=1
WARNING:root:Calculating choices
WARNING:root:*** Querying data ***
WARNING:root:http://0.0.0.0:8000/api/v1/interventions_elastic/?format=json&page_size=2000&normed=true
WARNING:root:http://0.0.0.0:8000/api/v1/interventions_elastic/?format=json&page_size=2000&normed=true&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_individuals/?format=json&page_size=2000
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_individuals/?format=json&page_size=2000&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_groups/?format=json&page_size=2000&measurement_type=smoking&choice=Y
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_groups/?format=json&page_size=2000&measurement_type=smoking&choice=Y&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/timecourse_intervention/?format=json&page_size=2000&normed=true
WARNING:root:http://0.0.0.0:8000/api/v1/timecourse_intervention/?format=json&page_size=2000&normed=true&page=1
WARNING:root:Calculating choices

In [111]:
data_both = data_smoking & data_healthy

WARNING:root:Calculating choices

   study_sid study_name  group_pk group_name  group_count  group_parent_pk  \
0  PKDB99999      Test1        13        all            6               -1
3  PKDB99999      Test1        13        all            6               -1

   characteristica_pk  count measurement_type choice  ... value  mean  median  \
0                 385      1          smoking      Y  ...   NaN   NaN     NaN
3                 384      6          healthy      Y  ...   NaN   NaN     NaN

   min  max  sd  se  cv  unit  pk
0  NaN  NaN NaN NaN NaN  None  13
3  NaN  NaN NaN NaN NaN  None  13

[2 rows x 21 columns]

In [112]:
data_both._len

1019

In [114]:
data_both.concise()

WARNING:root:Consice DataFrames

In [140]:
d = data_both
print("groups")
display(d.groups)
print("individuals")
display(d.individuals)
print("interventions")
display(d.interventions)
print("outputs")
display(d.outputs)
print("timecourses")
display(d.timecourses)

groups

,study_sid,study_name,group_pk,group_name,group_count,group_parent_pk,characteristica_pk,count,measurement_type,choice,substance,value,mean,median,min,max,sd,se,cv,unit
0,PKDB99999,Test1,13,all,6,-1,384,6,healthy,Y,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
1,PKDB99999,Test1,13,all,6,-1,385,1,smoking,Y,tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
2,PKDB99999,Test1,13,all,6,-1,386,5,smoking,N,coffee,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
3,PKDB99999,Test1,13,all,6,-1,387,6,age,None,None,NaN,NaN,NaN,25.0,37.0,NaN,NaN,NaN,yr
4,PKDB99999,Test1,13,all,6,-1,388,6,overnight fast,Y,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
5,PKDB99999,Test1,13,all,6,-1,383,6,species,homo sapiens,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None

individuals

,study_sid,study_name,individual_pk,individual_name,individual_group_pk,characteristica_pk,count,measurement_type,choice,substance,value,mean,median,min,max,sd,se,cv,unit
0,8549036,Backman1996,12,p06,2,62,10,fasting (duration),None,None,NaN,NaN,NaN,0.125000,NaN,NaN,NaN,NaN,day
1,8549036,Backman1996,12,p06,2,61,10,abstinence,None,tea,NaN,NaN,NaN,6.000000,NaN,NaN,NaN,NaN,day
2,8549036,Backman1996,12,p06,2,60,10,abstinence,None,coffee,NaN,NaN,NaN,6.000000,NaN,NaN,NaN,NaN,day
3,8549036,Backman1996,12,p06,2,59,10,abstinence smoking,None,None,NaN,NaN,NaN,0.016427,NaN,NaN,NaN,NaN,yr
4,8549036,Backman1996,12,p06,2,58,10,abstinence alcohol,None,None,NaN,NaN,NaN,6.000000,NaN,NaN,NaN,NaN,day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253,PKDB99999,Test1,65,FS,13,407,1,weight,None,None,78.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,kilogram
254,PKDB99999,Test1,65,FS,13,388,6,overnight fast,Y,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
255,PKDB99999,Test1,65,FS,13,386,5,smoking,N,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
256,PKDB99999,Test1,65,FS,13,385,1,smoking,Y,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
257,PKDB99999,Test1,65,FS,13,384,6,healthy,Y,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None

interventions

,study_sid,study_name,pk,raw_pk,normed,name,route,form,application,time,...,substance,value,mean,median,min,max,sd,se,cv,unit
0,8549036,Backman1996,8,7,True,MID,oral,tablet,single dose,0.0,...,midazolam,0.015000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gram
1,8549036,Backman1996,10,9,True,RIF,oral,capsule,multiple dose,-5.0,...,rifampicin,0.025000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gram / hour
2,2932334,Bornemann1985,28,25,True,po_30mg,oral,solution,single dose,0.0,...,midazolam,0.030000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gram
3,2932334,Bornemann1985,27,24,True,po_15mg,oral,solution,single dose,0.0,...,midazolam,0.015000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gram
4,2932334,Bornemann1985,26,23,True,po_7.5mg,oral,solution,single dose,0.0,...,midazolam,0.007500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gram
5,PKDB99999,Test1,83,81,True,po75,oral,tablet,single dose,0.0,...,midazolam,0.007500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gram
6,PKDB99999,Test1,84,82,True,po15,oral,tablet,single dose,0.0,...,midazolam,0.015000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gram
7,PKDB99999,Test1,86,85,True,iv,iv,solution,single dose,0.0,...,midazolam,0.000075,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gram / kilogram

outputs

,study_sid,study_name,output_pk,intervention_pk,group_pk,individual_pk,normed,calculated,tissue,time,...,substance,value,mean,median,min,max,sd,se,cv,unit
0,8549036,Backman1996,298,8,-1,14,True,False,plasma,NaN,...,midazolam,0.000074,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gram / liter
1,8549036,Backman1996,304,10,-1,10,True,False,plasma,NaN,...,midazolam,0.000004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gram / liter
2,8549036,Backman1996,306,8,-1,12,True,False,plasma,NaN,...,midazolam,0.000002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gram / liter
3,8549036,Backman1996,307,10,-1,13,True,False,plasma,NaN,...,midazolam,0.000005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gram / liter
4,8549036,Backman1996,308,10,-1,14,True,False,plasma,NaN,...,midazolam,0.000008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gram / liter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
328,PKDB99999,Test1,1646,84,-1,62,True,False,plasma,NaN,...,midazolam,1.800000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hour
329,PKDB99999,Test1,1643,84,-1,62,True,False,plasma,NaN,...,midazolam,0.070000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hour
330,PKDB99999,Test1,1661,83,-1,63,True,False,plasma,NaN,...,midazolam,0.330000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hour
331,PKDB99999,Test1,1660,83,-1,63,True,False,plasma,NaN,...,midazolam,0.080000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hour
332,PKDB99999,Test1,1633,83,-1,61,True,False,plasma,NaN,...,midazolam,0.330000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hour

timecourses

,study_sid,study_name,timecourse_pk,intervention_pk,group_pk,individual_pk,normed,tissue,time,time_unit,...,substance,value,mean,median,min,max,sd,se,cv,unit
0,PKDB99999,Test1,45,86,13,-1,True,plasma,"[0.00e+00, 1.70e-01, 3.30e-01, 5.00e-01, 7.50e...",hr,...,midazolam,None,"[1.85e-04, 1.44e-04, 1.21e-04, 1.06e-04, 8.38e...",None,None,None,"[2.33e-05, 1.82e-05, 2.06e-05, 2.68e-05, 1.03e...","[9.52e-06, 7.42e-06, 8.40e-06, 1.09e-05, 4.19e...","[1.26e-01, 1.26e-01, 1.71e-01, 2.53e-01, 1.23e...",gram / liter
1,PKDB99999,Test1,46,84,13,-1,True,plasma,"[1.70e-01, 3.30e-01, 7.50e-01, 1.00e+00, 1.50e...",hr,...,midazolam,None,"[1.01e-05, 1.32e-04, 1.34e-04, 9.67e-05, 9.66e...",None,None,None,"[4.76e-06, 7.49e-05, 3.01e-05, 4.23e-05, 5.29e...","[1.94e-06, 3.06e-05, 1.23e-05, 1.73e-05, 2.16e...","[4.71e-01, 5.66e-01, 2.24e-01, 4.37e-01, 5.48e...",gram / liter

In [70]:
from copy import deepcopy
d = deepcopy(data_healthy)
d.concise()

In [72]:
data_healthy._len

1021

In [74]:
group_pks = set(d.groups["group_pk"])
outputs_group_pks = set(d.outputs["group_pk"])
print(group_pks)
print(outputs_group_pks)
print(group_pks.intersection(outputs_group_pks))

{2, 4, 13, 6}
{2, 4, 6, 13, -1}
{2, 4, 13, 6}

In [69]:
group_pks = set(data_healthy.groups["group_pk"])
outputs_group_pks = set(data_healthy.outputs["group_pk"])
print(group_pks)
print(outputs_group_pks)
print(group_pks.intersection(outputs_group_pks))

{2, 4, 13, 6}
{2, 4, 6, 11, 13, -1}
{2, 4, 13, 6}

In [57]:
pkfilter_smoking = PKFilter()
pkfilter_smoking.groups["measurement_type"] = "smoking"
pkfilter_smoking.groups["choice"] = "Y"

data_smoking = PKData.from_db(pkfilter=pkfilter_smoking)

WARNING:root:*** Querying data ***
WARNING:root:http://0.0.0.0:8000/api/v1/interventions_elastic/?format=json&page_size=2000&normed=true
WARNING:root:http://0.0.0.0:8000/api/v1/interventions_elastic/?format=json&page_size=2000&normed=true&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_individuals/?format=json&page_size=2000
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_individuals/?format=json&page_size=2000&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_groups/?format=json&page_size=2000&measurement_type=smoking&choice=Y
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_groups/?format=json&page_size=2000&measurement_type=smoking&choice=Y&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/timecourse_intervention/?format=json&page_size=2000&normed=true
WARNING:root:http://0.0.0.0:8000/api/v1/timecourse_intervention/?format=json&page_size=2000&normed=true&page=1
WARNING:root:Calculating choices

In [37]:
data_both = data_smoking | data_healthy

WARNING:root:Calculating choices

In [139]:
data_both = data_both.from_db_missing()

WARNING:root:*** Querying data ***
WARNING:root:http://0.0.0.0:8000/api/v1/interventions_elastic/?format=json&page_size=2000&normed=true&pk__in=8__10__28__27__26__83__84__86
WARNING:root:http://0.0.0.0:8000/api/v1/interventions_elastic/?format=json&page_size=2000&normed=true&pk__in=8__10__28__27__26__83__84__86&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_individuals/?format=json&page_size=2000&individual_pk__in=12__14__8__11__7__9__10__13__15__16__24__19__25__18__21__26__27__23__17__28__22__20__64__63__61__62__66__65
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_individuals/?format=json&page_size=2000&individual_pk__in=12__14__8__11__7__9__10__13__15__16__24__19__25__18__21__26__27__23__17__28__22__20__64__63__61__62__66__65&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_groups/?format=json&page_size=2000&group_pk__in=13
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_groups/?format=json&page_size=2000&group_pk__in=13&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true&output_pk__in=298__304__306__307__308__310__315__317__321__326__328__329__330__339__341__342__347__348__353__354__361__365__588__589__590__595__600__609__610__616__625__628__631__632__637__640__642__645__649__652__656__657__672__675__678__685__686__1734__1732__1713__1710__1689__1669__1666__1748__1746__1698__1695__1694__1673__1657__1648__1662__1634__293__300__316__322__324__325__327__334__346__349__351__352__359__367__369__584__587__601__603__627__638__641__646__647__648__654__666__673__674__679__682__683__1733__1730__1692__1691__1690__1681__1680__1678__1652__1651__1650__1641__1639__1623__1622__1747__1716__1686__1685__1684__1683__1658__1656__1647__1630__1629__1628__1665__297__303__305__309__318__331__332__333__335__337__343__344__345__350__356__360__362__363__364__370__592__593__598__599__606__607__611__612__618__621__622__626__629__633__634__639__651__655__658__662__663__664__667__668__669__671__684__688__1736__1712__1688__1679__1667__1653__1640__1625__1624__1752__1751__1696__1693__1687__1682__1671__1631__1626__291__292__295__299__302__312__319__320__323__340__355__358__366__368__583__585__591__594__597__602__604__605__615__619__635__636__643__644__653__659__661__665__670__677__687__1714__1677__1745__1720__1719__1715__1697__1676__1675__1674__1672__1659__1655__1645__1644__1627__1664__1663__1637__1636__1635__1632__294__296__301__311__313__314__336__338__357__586__596__608__613__614__617__620__623__624__630__650__660__676__680__681__689__690__1735__1731__1729__1711__1670__1668__1649__1642__1638__1621__1750__1749__1718__1717__1654__1646__1643__1661__1660__1633
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true&output_pk__in=298__304__306__307__308__310__315__317__321__326__328__329__330__339__341__342__347__348__353__354__361__365__588__589__590__595__600__609__610__616__625__628__631__632__637__640__642__645__649__652__656__657__672__675__678__685__686__1734__1732__1713__1710__1689__1669__1666__1748__1746__1698__1695__1694__1673__1657__1648__1662__1634__293__300__316__322__324__325__327__334__346__349__351__352__359__367__369__584__587__601__603__627__638__641__646__647__648__654__666__673__674__679__682__683__1733__1730__1692__1691__1690__1681__1680__1678__1652__1651__1650__1641__1639__1623__1622__1747__1716__1686__1685__1684__1683__1658__1656__1647__1630__1629__1628__1665__297__303__305__309__318__331__332__333__335__337__343__344__345__350__356__360__362__363__364__370__592__593__598__599__606__607__611__612__618__621__622__626__629__633__634__639__651__655__658__662__663__664__667__668__669__671__684__688__1736__1712__1688__1679__1667__1653__1640__1625__1624__1752__1751__1696__1693__1687__1682__1671__1631__1626__291__292__295__299__302__312__319__320__323__340__355__358__366__368__583__585__591__594__597__602__604__605__615__619__635__636__643__644__653__659__661__665__670__677__687__1714__1677__1745__1720__1719__1715__1697__1676__1675__1674__1672__1659__1655__1645__1644__1627__1664__1663__1637__1636__1635__1632__294__296__301__311__313__314__336__338__357__586__596__608__613__614__617__620__623__624__630__650__660__676__680__681__689__690__1735__1731__1729__1711__1670__1668__1649__1642__1638__1621__1750__1749__1718__1717__1654__1646__1643__1661__1660__1633&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/timecourse_intervention/?format=json&page_size=2000&normed=true&timecourse_pk__in=45__46
WARNING:root:http://0.0.0.0:8000/api/v1/timecourse_intervention/?format=json&page_size=2000&normed=true&timecourse_pk__in=45__46&page=1
WARNING:root:Calculating choices

In [119]:
data_both

,study_sid,study_name,group_pk,group_name,group_count,group_parent_pk,characteristica_pk,count,measurement_type,choice,substance,value,mean,median,min,max,sd,se,cv,unit
0,PKDB99999,Test1,13,all,6,-1,384,6,healthy,Y,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
1,PKDB99999,Test1,13,all,6,-1,385,1,smoking,Y,tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
2,PKDB99999,Test1,13,all,6,-1,386,5,smoking,N,coffee,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
3,PKDB99999,Test1,13,all,6,-1,387,6,age,None,None,NaN,NaN,NaN,25.0,37.0,NaN,NaN,NaN,yr
4,PKDB99999,Test1,13,all,6,-1,388,6,overnight fast,Y,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
5,PKDB99999,Test1,13,all,6,-1,383,6,species,homo sapiens,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None

In [20]:
group_pks_url = "__".join([str(group_pk) for group_pk in data.groups.group_pk.unique()])
pkfilter.outputs["group_pk__in"] = group_pks_url
data = PKData.from_db(pkfilter=pkfilter)

WARNING:root:*** Querying data ***
WARNING:root:http://0.0.0.0:8000/api/v1/interventions_elastic/?format=json&page_size=2000&normed=true
WARNING:root:http://0.0.0.0:8000/api/v1/interventions_elastic/?format=json&page_size=2000&normed=true&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_individuals/?format=json&page_size=2000
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_individuals/?format=json&page_size=2000&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_groups/?format=json&page_size=2000&measurement_type=healthy&choice=Y
WARNING:root:http://0.0.0.0:8000/api/v1/characteristica_groups/?format=json&page_size=2000&measurement_type=healthy&choice=Y&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true&group_pk__in=2__4__6__13
WARNING:root:http://0.0.0.0:8000/api/v1/output_intervention/?format=json&page_size=2000&normed=true&group_pk__in=2__4__6__13&page=1
WARNING:root:http://0.0.0.0:8000/api/v1/timecourse_intervention/?format=json&page_size=2000&normed=true
WARNING:root:http://0.0.0.0:8000/api/v1/timecourse_intervention/?format=json&page_size=2000&normed=true&page=1
WARNING:root:Calculating choices

In [22]:
group_pks_url

'2__4__6__13'

In [21]:
data.outputs

,study_sid,study_name,output_pk,intervention_pk,group_pk,individual_pk,normed,calculated,tissue,time,...,substance,value,mean,median,min,max,sd,se,cv,unit
0,8549036,Backman1996,398,8,2,-1,True,True,plasma,NaN,...,midazolam,NaN,0.000002,NaN,NaN,NaN,NaN,NaN,NaN,gram / liter
1,8549036,Backman1996,398,10,2,-1,True,True,plasma,NaN,...,midazolam,NaN,0.000002,NaN,NaN,NaN,NaN,NaN,NaN,gram / liter
2,8549036,Backman1996,399,10,2,-1,True,True,plasma,NaN,...,midazolam,NaN,0.007450,NaN,NaN,NaN,NaN,NaN,NaN,1 / minute
3,8549036,Backman1996,402,10,2,-1,True,True,plasma,NaN,...,midazolam,NaN,1.500000,NaN,NaN,NaN,NaN,NaN,NaN,hour
4,2932334,Bornemann1985,443,27,4,-1,True,False,plasma,NaN,...,midazolam,NaN,0.810000,NaN,0.5,2.0,0.440000,0.127000,0.543,hour
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,PKDB99999,Test1,1711,86,13,-1,True,False,plasma,NaN,...,midazolam,NaN,0.680000,NaN,NaN,NaN,0.150000,0.061200,0.221,liter / kilogram
264,PKDB99999,Test1,1750,84,13,-1,True,True,plasma,NaN,...,midazolam,NaN,1.830000,NaN,NaN,NaN,NaN,NaN,NaN,hour
265,PKDB99999,Test1,1749,84,13,-1,True,True,plasma,NaN,...,midazolam,NaN,0.006300,NaN,NaN,NaN,NaN,NaN,NaN,1 / minute
266,PKDB99999,Test1,1718,84,13,-1,True,False,plasma,NaN,...,midazolam,NaN,2.100000,NaN,NaN,NaN,0.500000,0.204000,0.238,hour
267,PKDB99999,Test1,1717,84,13,-1,True,False,plasma,NaN,...,midazolam,NaN,0.000154,NaN,NaN,NaN,0.000051,0.000021,0.331,gram / liter

## 3 Query interventions
### 3.1 Get outputs/timecourses for intervention with substance
intervention with measurement_type "dosing" and substance "caffeine"
### 3.2 Get outputs/timecourses where multiple interventions were given

## 4 Query outputs/timecourses
### 4.1 query by measurement_type
### 4.2 complex
query all outputs