In [28]:
%load_ext autoreload
%autoreload 2
from IPython.display import display
from pkdb_analysis import PKFilter, PKFilterFactory, PKData, PKDB
import pandas as pd

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

# Curation and checking of studies
Helpers for simple checking of curated results.

In [29]:
# get data for study
study_name = "Test1"
pkfilter = PKFilterFactory.by_study_name(study_name)
data = PKDB.query(pkfilter=pkfilter)
print(data)

INFO *** Querying data ***
INFO http://0.0.0.0:8000/api/v1/pkdata/studies/?format=json&page_size=2000&study_name=Test1
INFO http://0.0.0.0:8000/api/v1/pkdata/studies/?format=json&page_size=2000&study_name=Test1&page=1
INFO http://0.0.0.0:8000/api/v1/pkdata/interventions/?format=json&page_size=2000&normed=true&study_name=Test1
INFO http://0.0.0.0:8000/api/v1/pkdata/interventions/?format=json&page_size=2000&normed=true&study_name=Test1&page=1
INFO http://0.0.0.0:8000/api/v1/pkdata/individuals/?format=json&page_size=2000&study_name=Test1
INFO http://0.0.0.0:8000/api/v1/pkdata/individuals/?format=json&page_size=2000&study_name=Test1&page=1
INFO http://0.0.0.0:8000/api/v1/pkdata/groups/?format=json&page_size=2000&study_name=Test1
INFO http://0.0.0.0:8000/api/v1/pkdata/groups/?format=json&page_size=2000&study_name=Test1&page=1
INFO http://0.0.0.0:8000/api/v1/pkdata/outputs/?format=json&page_size=2000&normed=true&study_name=Test1
INFO http://0.0.0.0:8000/api/v1/pkdata/outputs/?format=json&page_size=2000&normed=true&study_name=Test1&page=1
INFO http://0.0.0.0:8000/api/v1/pkdata/timecourses/?format=json&page_size=2000&study_name=Test1
INFO http://0.0.0.0:8000/api/v1/pkdata/timecourses/?format=json&page_size=2000&study_name=Test1&page=1

   intervention_pk_updated intervention_pk
0                        0          (3576)
1                        1          (3574)
2                        2          (3573)
------------------------------
PKData (140471378763216)
------------------------------
studies             1  (    1)
groups              1  (    7)
individuals         6  (   48)
interventions       3  (    3)
outputs           131  (  131)
timecourses         2  (    2)
------------------------------

## Explore data content

In [30]:
print(data.groups.pks)
print(data.individuals.pks)

{1826}
{7860, 7861, 7862, 7863, 7864, 7865}

In [31]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(data.groups_mi)
    display(data.individuals_mi)
    display(data.interventions_mi)
    display(data.outputs_mi)
    display(data.timecourses_mi)

                            study_sid study_name group_name  group_count  \
group_pk characteristica_pk
1826     35584                  Test1      Test1        all            6
         35585                  Test1      Test1        all            6
         35586                  Test1      Test1        all            6
         35587                  Test1      Test1        all            6
         35588                  Test1      Test1        all            6
         35589                  Test1      Test1        all            6
         35590                  Test1      Test1        all            6

                             group_parent_pk  count measurement_type  \
group_pk characteristica_pk
1826     35584                            -1      6          species
         35585                            -1      6          healthy
         35586                            -1      1          smoking
         35587                            -1      5          smoking
         35588                            -1      6              age
         35589                            -1      6   overnight fast
         35590                            -1      6              sex

                                   choice substance  value  mean  median  \
group_pk characteristica_pk
1826     35584               homo sapiens       nan    NaN   NaN     NaN
         35585                          Y       nan    NaN   NaN     NaN
         35586                          Y       nan    NaN   NaN     NaN
         35587                          N       nan    NaN   NaN     NaN
         35588                       None       nan    NaN   NaN     NaN
         35589                          Y       nan    NaN   NaN     NaN
         35590                         NR       nan    NaN   NaN     NaN

                              min   max  sd  se  cv  unit
group_pk characteristica_pk
1826     35584                NaN   NaN NaN NaN NaN  None
         35585                NaN   NaN NaN NaN NaN  None
         35586                NaN   NaN NaN NaN NaN  None
         35587                NaN   NaN NaN NaN NaN  None
         35588               25.0  37.0 NaN NaN NaN  year
         35589                NaN   NaN NaN NaN NaN  None
         35590                NaN   NaN NaN NaN NaN  None

                            study_sid study_name group_name  group_count  \
group_pk characteristica_pk
1826     35584                  Test1      Test1        all            6
         35585                  Test1      Test1        all            6
         35586                  Test1      Test1        all            6
         35587                  Test1      Test1        all            6
         35588                  Test1      Test1        all            6
         35589                  Test1      Test1        all            6
         35590                  Test1      Test1        all            6

                             group_parent_pk  count measurement_type  \
group_pk characteristica_pk
1826     35584                            -1      6          species
         35585                            -1      6          healthy
         35586                            -1      1          smoking
         35587                            -1      5          smoking
         35588                            -1      6              age
         35589                            -1      6   overnight fast
         35590                            -1      6              sex

                                   choice substance  value  mean  median  \
group_pk characteristica_pk
1826     35584               homo sapiens       nan    NaN   NaN     NaN
         35585                          Y       nan    NaN   NaN     NaN
         35586                          Y       nan    NaN   NaN     NaN
         35587                          N       nan    NaN   NaN     NaN
         35588                       None       nan    NaN   NaN     NaN
         35589                          Y       nan    NaN   NaN     NaN
         35590                         NR       nan    NaN   NaN     NaN

                              min   max  sd  se  cv  unit
group_pk characteristica_pk
1826     35584                NaN   NaN NaN NaN NaN  None
         35585                NaN   NaN NaN NaN NaN  None
         35586                NaN   NaN NaN NaN NaN  None
         35587                NaN   NaN NaN NaN NaN  None
         35588               25.0  37.0 NaN NaN NaN  year
         35589                NaN   NaN NaN NaN NaN  None
         35590                NaN   NaN NaN NaN NaN  None

                                                 study_sid study_name  \
individual_pk individual_name characteristica_pk
7860          WS              35584                  Test1      Test1
                              35585                  Test1      Test1
                              35586                  Test1      Test1
                              35587                  Test1      Test1
                              35589                  Test1      Test1
                              35590                  Test1      Test1
                              35593                  Test1      Test1
                              35594                  Test1      Test1
7861          HA              35584                  Test1      Test1
                              35585                  Test1      Test1
                              35586                  Test1      Test1
                              35587                  Test1      Test1
                              35589                  Test1      Test1
                              35590                  Test1      Test1
                              35597                  Test1      Test1
                              35598                  Test1      Test1
7862          TF              35584                  Test1      Test1
                              35585                  Test1      Test1
                              35586                  Test1      Test1
                              35587                  Test1      Test1
                              35589                  Test1      Test1
                              35590                  Test1      Test1
                              35601                  Test1      Test1
                              35602                  Test1      Test1
7863          UK              35584                  Test1      Test1
                              35585                  Test1      Test1
                              35586                  Test1      Test1
                              35587                  Test1      Test1
                              35589                  Test1      Test1
                              35590                  Test1      Test1
                              35605                  Test1      Test1
                              35606                  Test1      Test1
7864          FS              35584                  Test1      Test1
                              35585                  Test1      Test1
                              35586                  Test1      Test1
                              35587                  Test1      Test1
                              35589                  Test1      Test1
                              35590                  Test1      Test1
                              35609                  Test1      Test1
                              35610                  Test1      Test1
7865          GZ              35584                  Test1      Test1
                              35585                  Test1      Test1
                              35586                  Test1      Test1
                              35587                  Test1      Test1
                              35589                  Test1      Test1
                              35590                  Test1      Test1
                              35613                  Test1      Test1
                              35614                  Test1      Test1

                                                  individual_group_pk  count  \
individual_pk individual_name characteristica_pk
7860          WS              35584                              1826      6
                              35585                              1826      6
                              35586                              1826      1
                              35587                              1826      5
                              35589                              1826      6
                              35590                              1826      6
                              35593                              1826      1
                              35594                              1826      1
7861          HA              35584                              1826      6
                              35585                              1826      6
                              35586                              1826      1
                              35587                              1826      5
                              35589                              1826      6
                              35590                              1826      6
                              35597                              1826      1
                              35598                              1826      1
7862          TF              35584                              1826      6
                              35585                              1826      6
                              35586                              1826      1
                              35587                              1826      5
                              35589                              1826      6
                              35590                              1826      6
                              35601                              1826      1
                              35602                              1826      1
7863          UK              35584                              1826      6
                              35585                              1826      6
                              35586                              1826      1
                              35587                              1826      5
                              35589                              1826      6
                              35590                              1826      6
                              35605                              1826      1
                              35606                              1826      1
7864          FS              35584                              1826      6
                              35585                              1826      6
                              35586                              1826      1
                              35587                              1826      5
                              35589                              1826      6
                              35590                              1826      6
                              35609                              1826      1
                              35610                              1826      1
7865          GZ              35584                              1826      6
                              35585                              1826      6
                              35586                              1826      1
                              35587                              1826      5
                              35589                              1826      6
                              35590                              1826      6
                              35613                              1826      1
                              35614                              1826      1

                                                 measurement_type  \
individual_pk individual_name characteristica_pk
7860          WS              35584                       species
                              35585                       healthy
                              35586                       smoking
                              35587                       smoking
                              35589                overnight fast
                              35590                           sex
                              35593                        weight
                              35594                           age
7861          HA              35584                       species
                              35585                       healthy
                              35586                       smoking
                              35587                       smoking
                              35589                overnight fast
                              35590                           sex
                              35597                        weight
                              35598                           age
7862          TF              35584                       species
                              35585                       healthy
                              35586                       smoking
                              35587                       smoking
                              35589                overnight fast
                              35590                           sex
                              35601                        weight
                              35602                           age
7863          UK              35584                       species
                              35585                       healthy
                              35586                       smoking
                              35587                       smoking
                              35589                overnight fast
                              35590                           sex
                              35605                        weight
                              35606                           age
7864          FS              35584                       species
                              35585                       healthy
                              35586                       smoking
                              35587                       smoking
                              35589                overnight fast
                              35590                           sex
                              35609                        weight
                              35610                           age
7865          GZ              35584                       species
                              35585                       healthy
                              35586                       smoking
                              35587                       smoking
                              35589                overnight fast
                              35590                           sex
                              35613                        weight
                              35614                           age

                                                        choice substance  \
individual_pk individual_name characteristica_pk
7860          WS              35584               homo sapiens       nan
                              35585                          Y       nan
                              35586                          Y       nan
                              35587                          N       nan
                              35589                          Y       nan
                              35590                         NR       nan
                              35593                       None       nan
                              35594                       None       nan
7861          HA              35584               homo sapiens       nan
                              35585                          Y       nan
                              35586                          Y       nan
                              35587                          N       nan
                              35589                          Y       nan
                              35590                         NR       nan
                              35597                       None       nan
                              35598                       None       nan
7862          TF              35584               homo sapiens       nan
                              35585                          Y       nan
                              35586                          Y       nan
                              35587                          N       nan
                              35589                          Y       nan
                              35590                         NR       nan
                              35601                       None       nan
                              35602                       None       nan
7863          UK              35584               homo sapiens       nan
                              35585                          Y       nan
                              35586                          Y       nan
                              35587                          N       nan
                              35589                          Y       nan
                              35590                         NR       nan
                              35605                       None       nan
                              35606                       None       nan
7864          FS              35584               homo sapiens       nan
                              35585                          Y       nan
                              35586                          Y       nan
                              35587                          N       nan
                              35589                          Y       nan
                              35590                         NR       nan
                              35609                       None       nan
                              35610                       None       nan
7865          GZ              35584               homo sapiens       nan
                              35585                          Y       nan
                              35586                          Y       nan
                              35587                          N       nan
                              35589                          Y       nan
                              35590                         NR       nan
                              35613                       None       nan
                              35614                       None       nan

                                                  value  mean  median  min  \
individual_pk individual_name characteristica_pk
7860          WS              35584                 NaN   NaN     NaN  NaN
                              35585                 NaN   NaN     NaN  NaN
                              35586                 NaN   NaN     NaN  NaN
                              35587                 NaN   NaN     NaN  NaN
                              35589                 NaN   NaN     NaN  NaN
                              35590                 NaN   NaN     NaN  NaN
                              35593                74.0   NaN     NaN  NaN
                              35594                25.0   NaN     NaN  NaN
7861          HA              35584                 NaN   NaN     NaN  NaN
                              35585                 NaN   NaN     NaN  NaN
                              35586                 NaN   NaN     NaN  NaN
                              35587                 NaN   NaN     NaN  NaN
                              35589                 NaN   NaN     NaN  NaN
                              35590                 NaN   NaN     NaN  NaN
                              35597                59.0   NaN     NaN  NaN
                              35598                32.0   NaN     NaN  NaN
7862          TF              35584                 NaN   NaN     NaN  NaN
                              35585                 NaN   NaN     NaN  NaN
                              35586                 NaN   NaN     NaN  NaN
                              35587                 NaN   NaN     NaN  NaN
                              35589                 NaN   NaN     NaN  NaN
                              35590                 NaN   NaN     NaN  NaN
                              35601                63.0   NaN     NaN  NaN
                              35602                27.0   NaN     NaN  NaN
7863          UK              35584                 NaN   NaN     NaN  NaN
                              35585                 NaN   NaN     NaN  NaN
                              35586                 NaN   NaN     NaN  NaN
                              35587                 NaN   NaN     NaN  NaN
                              35589                 NaN   NaN     NaN  NaN
                              35590                 NaN   NaN     NaN  NaN
                              35605                67.0   NaN     NaN  NaN
                              35606                37.0   NaN     NaN  NaN
7864          FS              35584                 NaN   NaN     NaN  NaN
                              35585                 NaN   NaN     NaN  NaN
                              35586                 NaN   NaN     NaN  NaN
                              35587                 NaN   NaN     NaN  NaN
                              35589                 NaN   NaN     NaN  NaN
                              35590                 NaN   NaN     NaN  NaN
                              35609                78.0   NaN     NaN  NaN
                              35610                29.0   NaN     NaN  NaN
7865          GZ              35584                 NaN   NaN     NaN  NaN
                              35585                 NaN   NaN     NaN  NaN
                              35586                 NaN   NaN     NaN  NaN
                              35587                 NaN   NaN     NaN  NaN
                              35589                 NaN   NaN     NaN  NaN
                              35590                 NaN   NaN     NaN  NaN
                              35613                79.0   NaN     NaN  NaN
                              35614                29.0   NaN     NaN  NaN

                                                  max  sd  se  cv      unit
individual_pk individual_name characteristica_pk
7860          WS              35584               NaN NaN NaN NaN      None
                              35585               NaN NaN NaN NaN      None
                              35586               NaN NaN NaN NaN      None
                              35587               NaN NaN NaN NaN      None
                              35589               NaN NaN NaN NaN      None
                              35590               NaN NaN NaN NaN      None
                              35593               NaN NaN NaN NaN  kilogram
                              35594               NaN NaN NaN NaN      year
7861          HA              35584               NaN NaN NaN NaN      None
                              35585               NaN NaN NaN NaN      None
                              35586               NaN NaN NaN NaN      None
                              35587               NaN NaN NaN NaN      None
                              35589               NaN NaN NaN NaN      None
                              35590               NaN NaN NaN NaN      None
                              35597               NaN NaN NaN NaN  kilogram
                              35598               NaN NaN NaN NaN      year
7862          TF              35584               NaN NaN NaN NaN      None
                              35585               NaN NaN NaN NaN      None
                              35586               NaN NaN NaN NaN      None
                              35587               NaN NaN NaN NaN      None
                              35589               NaN NaN NaN NaN      None
                              35590               NaN NaN NaN NaN      None
                              35601               NaN NaN NaN NaN  kilogram
                              35602               NaN NaN NaN NaN      year
7863          UK              35584               NaN NaN NaN NaN      None

                                                 study_sid study_name  \
individual_pk individual_name characteristica_pk
7860          WS              35584                  Test1      Test1
                              35585                  Test1      Test1
                              35586                  Test1      Test1
                              35587                  Test1      Test1
                              35589                  Test1      Test1
                              35590                  Test1      Test1
                              35593                  Test1      Test1
                              35594                  Test1      Test1
7861          HA              35584                  Test1      Test1
                              35585                  Test1      Test1
                              35586                  Test1      Test1
                              35587                  Test1      Test1
                              35589                  Test1      Test1
                              35590                  Test1      Test1
                              35597                  Test1      Test1
                              35598                  Test1      Test1
7862          TF              35584                  Test1      Test1
                              35585                  Test1      Test1
                              35586                  Test1      Test1
                              35587                  Test1      Test1
                              35589                  Test1      Test1
                              35590                  Test1      Test1
                              35601                  Test1      Test1
                              35602                  Test1      Test1
7863          UK              35584                  Test1      Test1
                              35585                  Test1      Test1
                              35586                  Test1      Test1
                              35587                  Test1      Test1
                              35589                  Test1      Test1
                              35590                  Test1      Test1
                              35605                  Test1      Test1
                              35606                  Test1      Test1
7864          FS              35584                  Test1      Test1
                              35585                  Test1      Test1
                              35586                  Test1      Test1
                              35587                  Test1      Test1
                              35589                  Test1      Test1
                              35590                  Test1      Test1
                              35609                  Test1      Test1
                              35610                  Test1      Test1
7865          GZ              35584                  Test1      Test1
                              35585                  Test1      Test1
                              35586                  Test1      Test1
                              35587                  Test1      Test1
                              35589                  Test1      Test1
                              35590                  Test1      Test1
                              35613                  Test1      Test1
                              35614                  Test1      Test1

                                                  individual_group_pk  count  \
individual_pk individual_name characteristica_pk
7860          WS              35584                              1826      6
                              35585                              1826      6
                              35586                              1826      1
                              35587                              1826      5
                              35589                              1826      6
                              35590                              1826      6
                              35593                              1826      1
                              35594                              1826      1
7861          HA              35584                              1826      6
                              35585                              1826      6
                              35586                              1826      1
                              35587                              1826      5
                              35589                              1826      6
                              35590                              1826      6
                              35597                              1826      1
                              35598                              1826      1
7862          TF              35584                              1826      6
                              35585                              1826      6
                              35586                              1826      1
                              35587                              1826      5
                              35589                              1826      6
                              35590                              1826      6
                              35601                              1826      1
                              35602                              1826      1
7863          UK              35584                              1826      6
                              35585                              1826      6
                              35586                              1826      1
                              35587                              1826      5
                              35589                              1826      6
                              35590                              1826      6
                              35605                              1826      1
                              35606                              1826      1
7864          FS              35584                              1826      6
                              35585                              1826      6
                              35586                              1826      1
                              35587                              1826      5
                              35589                              1826      6
                              35590                              1826      6
                              35609                              1826      1
                              35610                              1826      1
7865          GZ              35584                              1826      6
                              35585                              1826      6
                              35586                              1826      1
                              35587                              1826      5
                              35589                              1826      6
                              35590                              1826      6
                              35613                              1826      1
                              35614                              1826      1

                                                 measurement_type  \
individual_pk individual_name characteristica_pk
7860          WS              35584                       species
                              35585                       healthy
                              35586                       smoking
                              35587                       smoking
                              35589                overnight fast
                              35590                           sex
                              35593                        weight
                              35594                           age
7861          HA              35584                       species
                              35585                       healthy
                              35586                       smoking
                              35587                       smoking
                              35589                overnight fast
                              35590                           sex
                              35597                        weight
                              35598                           age
7862          TF              35584                       species
                              35585                       healthy
                              35586                       smoking
                              35587                       smoking
                              35589                overnight fast
                              35590                           sex
                              35601                        weight
                              35602                           age
7863          UK              35584                       species
                              35585                       healthy
                              35586                       smoking
                              35587                       smoking
                              35589                overnight fast
                              35590                           sex
                              35605                        weight
                              35606                           age
7864          FS              35584                       species
                              35585                       healthy
                              35586                       smoking
                              35587                       smoking
                              35589                overnight fast
                              35590                           sex
                              35609                        weight
                              35610                           age
7865          GZ              35584                       species
                              35585                       healthy
                              35586                       smoking
                              35587                       smoking
                              35589                overnight fast
                              35590                           sex
                              35613                        weight
                              35614                           age

                                                        choice substance  \
individual_pk individual_name characteristica_pk
7860          WS              35584               homo sapiens       nan
                              35585                          Y       nan
                              35586                          Y       nan
                              35587                          N       nan
                              35589                          Y       nan
                              35590                         NR       nan
                              35593                       None       nan
                              35594                       None       nan
7861          HA              35584               homo sapiens       nan
                              35585                          Y       nan
                              35586                          Y       nan
                              35587                          N       nan
                              35589                          Y       nan
                              35590                         NR       nan
                              35597                       None       nan
                              35598                       None       nan
7862          TF              35584               homo sapiens       nan
                              35585                          Y       nan
                              35586                          Y       nan
                              35587                          N       nan
                              35589                          Y       nan
                              35590                         NR       nan
                              35601                       None       nan
                              35602                       None       nan
7863          UK              35584               homo sapiens       nan
                              35585                          Y       nan
                              35586                          Y       nan
                              35587                          N       nan
                              35589                          Y       nan
                              35590                         NR       nan
                              35605                       None       nan
                              35606                       None       nan
7864          FS              35584               homo sapiens       nan
                              35585                          Y       nan
                              35586                          Y       nan
                              35587                          N       nan
                              35589                          Y       nan
                              35590                         NR       nan
                              35609                       None       nan
                              35610                       None       nan
7865          GZ              35584               homo sapiens       nan
                              35585                          Y       nan
                              35586                          Y       nan
                              35587                          N       nan
                              35589                          Y       nan
                              35590                         NR       nan
                              35613                       None       nan
                              35614                       None       nan

                                                  value  mean  median  min  \
individual_pk individual_name characteristica_pk
7860          WS              35584                 NaN   NaN     NaN  NaN
                              35585                 NaN   NaN     NaN  NaN
                              35586                 NaN   NaN     NaN  NaN
                              35587                 NaN   NaN     NaN  NaN
                              35589                 NaN   NaN     NaN  NaN
                              35590                 NaN   NaN     NaN  NaN
                              35593                74.0   NaN     NaN  NaN
                              35594                25.0   NaN     NaN  NaN
7861          HA              35584                 NaN   NaN     NaN  NaN
                              35585                 NaN   NaN     NaN  NaN
                              35586                 NaN   NaN     NaN  NaN
                              35587                 NaN   NaN     NaN  NaN
                              35589                 NaN   NaN     NaN  NaN
                              35590                 NaN   NaN     NaN  NaN
                              35597                59.0   NaN     NaN  NaN
                              35598                32.0   NaN     NaN  NaN
7862          TF              35584                 NaN   NaN     NaN  NaN
                              35585                 NaN   NaN     NaN  NaN
                              35586                 NaN   NaN     NaN  NaN
                              35587                 NaN   NaN     NaN  NaN
                              35589                 NaN   NaN     NaN  NaN
                              35590                 NaN   NaN     NaN  NaN
                              35601                63.0   NaN     NaN  NaN
                              35602                27.0   NaN     NaN  NaN
7863          UK              35584                 NaN   NaN     NaN  NaN
                              35585                 NaN   NaN     NaN  NaN
                              35586                 NaN   NaN     NaN  NaN
                              35587                 NaN   NaN     NaN  NaN
                              35589                 NaN   NaN     NaN  NaN
                              35590                 NaN   NaN     NaN  NaN
                              35605                67.0   NaN     NaN  NaN
                              35606                37.0   NaN     NaN  NaN
7864          FS              35584                 NaN   NaN     NaN  NaN
                              35585                 NaN   NaN     NaN  NaN
                              35586                 NaN   NaN     NaN  NaN
                              35587                 NaN   NaN     NaN  NaN
                              35589                 NaN   NaN     NaN  NaN
                              35590                 NaN   NaN     NaN  NaN
                              35609                78.0   NaN     NaN  NaN
                              35610                29.0   NaN     NaN  NaN
7865          GZ              35584                 NaN   NaN     NaN  NaN
                              35585                 NaN   NaN     NaN  NaN
                              35586                 NaN   NaN     NaN  NaN
                              35587                 NaN   NaN     NaN  NaN
                              35589                 NaN   NaN     NaN  NaN
                              35590                 NaN   NaN     NaN  NaN
                              35613                79.0   NaN     NaN  NaN
                              35614                29.0   NaN     NaN  NaN

                                                  max  sd  se  cv      unit
individual_pk individual_name characteristica_pk
7860          WS              35584               NaN NaN NaN NaN      None
                              35585               NaN NaN NaN NaN      None
                              35586               NaN NaN NaN NaN      None
                              35587               NaN NaN NaN NaN      None
                              35589               NaN NaN NaN NaN      None
                              35590               NaN NaN NaN NaN      None
                              35593               NaN NaN NaN NaN  kilogram
                              35594               NaN NaN NaN NaN      year
7861          HA              35584               NaN NaN NaN NaN      None
                              35585               NaN NaN NaN NaN      None
                              35586               NaN NaN NaN NaN      None
                              35587               NaN NaN NaN NaN      None
                              35589               NaN NaN NaN NaN      None
                              35590               NaN NaN NaN NaN      None
                              35597               NaN NaN NaN NaN  kilogram
                              35598               NaN NaN NaN NaN      year
7862          TF              35584               NaN NaN NaN NaN      None
                              35585               NaN NaN NaN NaN      None
                              35586               NaN NaN NaN NaN      None
                              35587               NaN NaN NaN NaN      None
                              35589               NaN NaN NaN NaN      None
                              35590               NaN NaN NaN NaN      None
                              35601               NaN NaN NaN NaN  kilogram
                              35602               NaN NaN NaN NaN      year
7863          UK              35584               NaN NaN NaN NaN      None

,study_sid,study_name,raw_pk,normed,name,route,form,application,time,time_end,time_unit,measurement_type,choice,substance,value,mean,median,min,max,sd,se,cv,unit
intervention_pk,,,,,,,,,,,,,,,,,,,,,,,
0,Test1,Test1,3575,True,iv,iv,solution,single dose,0.0,None,hr,dosing,None,midazolam,7.500000e-08,None,None,None,None,None,None,None,count
1,Test1,Test1,3572,True,po15,oral,tablet,single dose,0.0,None,hr,dosing,None,midazolam,1.500000e-02,None,None,None,None,None,None,None,gram
2,Test1,Test1,3571,True,po75,oral,tablet,single dose,0.0,None,hr,dosing,None,midazolam,7.500000e-03,None,None,None,None,None,None,None,gram

                study_sid study_name  raw_pk  normed  name route      form  \
intervention_pk
0                   Test1      Test1    3575    True    iv    iv  solution
1                   Test1      Test1    3572    True  po15  oral    tablet
2                   Test1      Test1    3571    True  po75  oral    tablet

                 application  time time_end time_unit measurement_type choice  \
intervention_pk
0                single dose   0.0     None        hr           dosing   None
1                single dose   0.0     None        hr           dosing   None
2                single dose   0.0     None        hr           dosing   None

                 substance         value  mean median   min   max    sd    se  \
intervention_pk
0                midazolam  7.500000e-08  None   None  None  None  None  None
1                midazolam  1.500000e-02  None   None  None  None  None  None
2                midazolam  7.500000e-03  None   None  None  None  None  None

                   cv   unit
intervention_pk
0                None  count
1                None   gram
2                None   gram

,,,,study_sid,study_name,normed,calculated,tissue,method,label,output_type,time,time_unit,measurement_type,choice,substance,value,mean,median,min,max,sd,se,cv,unit
output_pk,intervention_pk,group_pk,individual_pk,,,,,,,,,,,,,,,,,,,,,,
183973,0,-1,7860,Test1,Test1,True,False,plasma,None,None,output,NaN,None,thalf,None,midazolam,2.300000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hour
183974,0,-1,7860,Test1,Test1,True,False,plasma,None,None,output,NaN,None,vd,None,midazolam,0.710000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,liter / kilogram
183975,0,-1,7860,Test1,Test1,True,False,plasma,None,None,output,NaN,None,clearance,None,midazolam,17.520000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,liter / hour
183976,0,-1,7860,Test1,Test1,True,False,plasma,None,None,output,NaN,None,clearance_unbound,None,midazolam,350.400000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,liter / hour
183977,0,-1,7860,Test1,Test1,True,False,plasma,None,None,output,NaN,None,plasma_binding,None,midazolam,0.950000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dimensionless
183978,1,-1,7860,Test1,Test1,True,False,plasma,None,None,output,NaN,None,thalf_absorption,None,midazolam,0.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hour
183979,1,-1,7860,Test1,Test1,True,False,plasma,None,None,output,NaN,None,tmax,None,midazolam,1.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hour
183980,1,-1,7860,Test1,Test1,True,False,plasma,None,None,output,NaN,None,cmax,None,midazolam,0.000204,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gram / liter
183981,1,-1,7860,Test1,Test1,True,False,plasma,None,None,output,NaN,None,thalf,None,midazolam,2.600000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hour
183982,1,-1,7860,Test1,Test1,True,False,plasma,None,None,output,NaN,None,clearance_intrinsic,None,midazolam,28.200000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,liter / hour
183983,1,-1,7860,Test1,Test1,True,False,plasma,None,None,output,NaN,None,fraction_absorbed,None,midazolam,0.590000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dimensionless
183984,2,-1,7860,Test1,Test1,True,False,plasma,None,None,output,NaN,None,thalf_absorption,None,midazolam,0.110000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hour
183985,2,-1,7860,Test1,Test1,True,False,plasma,None,None,output,NaN,None,tmax,None,midazolam,0.330000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hour
183986,2,-1,7860,Test1,Test1,True,False,plasma,None,None,output,NaN,None,cmax,None,midazolam,0.000128,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gram / liter
183987,2,-1,7860,Test1,Test1,True,False,plasma,None,None,output,NaN,None,thalf,None,midazolam,1.200000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hour
183988,2,-1,7860,Test1,Test1,True,False,plasma,None,None,output,NaN,None,clearance_intrinsic,None,midazolam,45.720000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,liter / hour
183989,2,-1,7860,Test1,Test1,True,False,plasma,None,None,output,NaN,None,fraction_absorbed,None,midazolam,0.360000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dimensionless
183990,0,-1,7861,Test1,Test1,True,False,plasma,None,None,output,NaN,None,thalf,None,midazolam,2.200000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hour
183991,0,-1,7861,Test1,Test1,True,False,plasma,None,None,output,NaN,None,vd,None,midazolam,0.910000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,liter / kilogram
183992,0,-1,7861,Test1,Test1,True,False,plasma,None,None,output,NaN,None,clearance,None,midazolam,19.440000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,liter / hour
183993,0,-1,7861,Test1,Test1,True,False,plasma,None,None,output,NaN,None,clearance_unbound,None,midazolam,243.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,liter / hour
183994,0,-1,7861,Test1,Test1,True,False,plasma,None,None,output,NaN,None,plasma_binding,None,midazolam,0.920000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dimensionless
183995,1,-1,7861,Test1,Test1,True,False,plasma,None,None,output,NaN,None,thalf_absorption,None,midazolam,0.070000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hour
183996,1,-1,7861,Test1,Test1,True,False,plasma,None,None,output,NaN,None,tmax,None,midazolam,0.330000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hour
183997,1,-1,7861,Test1,Test1,True,False,plasma,None,None,output,NaN,None,cmax,None,midazolam,0.000195,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gram / liter
183998,1,-1,7861,Test1,Test1,True,False,plasma,None,None,output,NaN,None,thalf,None,midazolam,1.800000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hour
183999,1,-1,7861,Test1,Test1,True,False,plasma,None,None,output,NaN,None,clearance_intrinsic,None,midazolam,42.240000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,liter / hour
184000,1,-1,7861,Test1,Test1,True,False,plasma,None,None,output,NaN,None,fraction_absorbed,None,midazolam,0.470000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dimensionless
184001,0,-1,7862,Test1,Test1,True,False,plasma,None,None,output,NaN,None,thalf,None,midazolam,2.300000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hour
184002,0,-1,7862,Test1,Test1,True,False,plasma,None,None,output,NaN,None,vd,None,midazolam,0.620000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,liter / kilogram
184003,0,-1,7862,Test1,Test1,True,False,plasma,None,None,output,NaN,None,clearance,None,midazolam,16.380000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,liter / hour
184004,0,-1,7862,Test1,Test1,True,False,plasma,None,None,output,NaN,None,clearance_unbound,None,midazolam,204.780000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,liter / hour
184005,0,-1,7862,Test1,Test1,True,False,plasma,None,None,output,NaN,None,plasma_binding,None,midazolam,0.920000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dimensionless
184006,1,-1,7862,Test1,Test1,True,False,plasma,None,None,output,NaN,None,thalf_absorption,None,midazolam,0.050000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hour
184007,1,-1,7862,Test1,Test1,True,False,plasma,None,None,output,NaN,None,tmax,None,midazolam,0.330000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hour
184008,1,-1,7862,Test1,Test1,True,False,plasma,None,None,output,NaN,None,cmax,None,midazolam,0.000152,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gram / liter
184009,1,-1,7862,Test1,Test1,True,False,plasma,None,None,output,NaN,None,thalf,None,midazolam,2.400000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hour
184010,1,-1,7862,Test1,Test1,True,False,plasma,None,None,output,NaN,None,clearance_intrinsic,None,midazolam,48.180000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,liter / hour
184011,1,-1,7862,Test1,Test1,True,False,plasma,None,None,output,NaN,None,fraction_absorbed,None,midazolam,0.350000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dimensionless
184012,2,-1,7862,Test1,Test1,True,False,plasma,None,None,output,NaN,None,thalf_absorption,None,midazolam,0.080000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hour
184013,2,-1,7862,Test1,Test1,True,False,plasma,None,None,output,NaN,None,tmax,None,midazolam,0.330000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hour
184014,2,-1,7862,Test1,Test1,True,False,plasma,None,None,output,NaN,None,cmax,None,midazolam,0.000075,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gram / liter
184015,2,-1,7862,Test1,Test1,True,False,plasma,None,None,output,NaN,None,thalf,None,midazolam,1.400000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hour
184016,2,-1,7862,Test1,Test1,True,False,plasma,None,None,output,NaN,None,clearance_intrinsic,None,midazolam,60.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,liter / hour
184017,2,-1,7862,Test1,Test1,True,False,plasma,None,None,output,NaN,None,fraction_absorbed,None,midazolam,0.280000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dimensionless
184018,0,-1,7863,Test1,Test1,True,False,plasma,None,None,output,NaN,None,thalf,None,midazolam,1.200000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hour
184019,0,-1,7863,Test1,Test1,True,False,plasma,None,None,output,NaN,None,vd,None,midazolam,0.440000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,liter / kilogram
184020,0,-1,7863,Test1,Test1,True,False,plasma,None,None,output,NaN,None,clearance,None,midazolam,17.940000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,liter / hour
184021,0,-1,7863,Test1,Test1,True,False,plasma,None,None,output,NaN,None,clearance_unbound,None,midazolam,35.880000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,liter / hour
184022,0,-1,7863,Test1,Test1,True,False,plasma,None,None,output,NaN,None,plasma_binding,None,midazolam,0.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dimensionless
184023,1,-1,7863,Test1,Test1,True,False,plasma,None,None,output,NaN,None,thalf_absorption,None,midazolam,1.140000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hour
184024,1,-1,7863,Test1,Test1,True,False,plasma,None,None,output,NaN,None,tmax,None,midazolam,1.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hour
184025,1,-1,7863,Test1,Test1,True,False,plasma,None,None,output,NaN,None,cmax,None,midazolam,0.000084,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gram / liter
184026,1,-1,7863,Test1,Test1,True,False,plasma,None,None,output,NaN,None,thalf,None,midazolam,1.300000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hour
184027,1,-1,7863,Test1,Test1,True,False,plasma,None,None,output,NaN,None,clearance_intrinsic,None,midazolam,46.560000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,liter / hour
184028,1,-1,7863,Test1,Test1,True,False,plasma,None,None,output,NaN,None,fraction_absorbed,None,midazolam,0.350000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dimensionless
184029,0,-1,7864,Test1,Test1,True,False,plasma,None,None,output,NaN,None,thalf,None,midazolam,3.800000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hour
184030,0,-1,7864,Test1,Test1,True,False,plasma,None,None,output,NaN,None,vd,None,midazolam,0.710000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,liter / kilogram
184031,0,-1,7864,Test1,Test1,True,False,plasma,None,None,output,NaN,None,clearance,None,midazolam,12.120000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,liter / hour
184032,0,-1,7864,Test1,Test1,True,False,plasma,None,None,output,NaN,None,clearance_unbound,None,midazolam,242.400000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,liter / hour
184033,0,-1,7864,Test1,Test1,True,False,plasma,None,None,output,NaN,None,plasma_binding,None,midazolam,0.950000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dimensionless
184034,1,-1,7864,Test1,Test1,True,False,plasma,None,None,output,NaN,None,thalf_absorption,None,midazolam,0.130000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hour
184035,1,-1,7864,Test1,Test1,True,False,plasma,None,None,output,NaN,None,tmax,None,midazolam,0.330000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hour
184036,1,-1,7864,Test1,Test1,True,False,plasma,None,None,output,NaN,None,cmax,None,midazolam,0.000185,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gram / liter
184037,1,-1,7864,Test1,Test1,True,False,plasma,None,None,output,NaN,None,thalf,None,midazolam,2.100000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hour
184038,1,-1,7864,Test1,Test1,True,False,plasma,None,None,output,NaN,None,clearance_intrinsic,None,midazolam,40.560000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,liter / hour
184039,1,-1,7864,Test1,Test1,True,False,plasma,None,None,output,NaN,None,fraction_absorbed,None,midazolam,0.210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dimensionless
184040,0,-1,7865,Test1,Test1,True,False,plasma,None,None,output,NaN,None,thalf,None,midazolam,2.300000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hour
184041,0,-1,7865,Test1,Test1,True,False,plasma,None,None,output,NaN,None,vd,None,midazolam,0.690000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,liter / kilogram
184042,0,-1,7865,Test1,Test1,True,False,plasma,None,None,output,NaN,None,clearance,None,midazolam,18.600000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,liter / hour
184043,0,-1,7865,Test1,Test1,True,False,plasma,None,None,output,NaN,None,clearance_unbound,None,midazolam,465.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,liter / hour
184044,0,-1,7865,Test1,Test1,True,False,plasma,None,None,output,NaN,None,plasma_binding,None,midazolam,0.960000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dimensionless
184045,1,-1,7865,Test1,Test1,True,False,plasma,None,None,output,NaN,None,thalf_absorption,None,midazolam,0.040000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hour
184046,1,-1,7865,Test1,Test1,True,False,plasma,None,None,output,NaN,None,tmax,None,midazolam,0.670000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hour
184047,1,-1,7865,Test1,Test1,True,False,plasma,None,None,output,NaN,None,cmax,None,midazolam,0.000101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gram / liter
184048,1,-1,7865,Test1,Test1,True,False,plasma,None,None,output,NaN,None,thalf,None,midazolam,2.100000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hour
184049,1,-1,7865,Test1,Test1,True,False,plasma,None,None,output,NaN,None,clearance_intrinsic,None,midazolam,26.400000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,liter / hour
184050,1,-1,7865,Test1,Test1,True,False,plasma,None,None,output,NaN,None,fraction_absorbed,None,midazolam,0.670000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dimensionless
184062,0,1826,-1,Test1,Test1,True,False,plasma,None,None,output,NaN,None,thalf,None,midazolam,NaN,2.400000,NaN,NaN,NaN,0.800000,0.326599,0.333333,hour
184063,0,1826,-1,Test1,Test1,True,False,plasma,None,None,output,NaN,None,vd,None,midazolam,NaN,0.680000,NaN,NaN,NaN,0.150000,0.061237,0.220588,liter / kilogram
184064,0,1826,-1,Test1,Test1,True,False,plasma,None,None,output,NaN,None,clearance,None,midazolam,NaN,16.980000,NaN,NaN,NaN,2.580000,1.053281,0.151943,liter / hour
184065,0,1826,-1,Test1,Test1,True,False,plasma,None,None,output,NaN,None,clearance_unbound,None,midazolam,NaN,301.140000,NaN,NaN,NaN,106.500000,43.478443,0.353656,liter / hour
184066,0,1826,-1,Test1,Test1,True,False,plasma,None,None,output,NaN,None,plasma_binding,None,midazolam,NaN,0.940000,NaN,NaN,NaN,0.019000,0.007757,0.020213,dimensionless
184067,1,1826,-1,Test1,Test1,True,False,plasma,None,None,output,NaN,None,thalf_absorption,None,midazolam,NaN,0.230000,NaN,NaN,NaN,0.370000,0.151052,1.608696,hour
184068,1,1826,-1,Test1,Test1,True,False,plasma,None,None,output,NaN,None,tmax,None,midazolam,NaN,0.670000,NaN,NaN,NaN,0.530000,0.216372,0.791045,hour
184069,1,1826,-1,Test1,Test1,True,False,plasma,None,None,output,NaN,None,cmax,None,midazolam,NaN,0.000154,NaN,NaN,NaN,0.000051,0.000021,0.331169,gram / liter
184070,1,1826,-1,Test1,Test1,True,False,plasma,None,None,output,NaN,None,thalf,None,midazolam,NaN,2.100000,NaN,NaN,NaN,0.500000,0.204124,0.238095,hour
184071,1,1826,-1,Test1,Test1,True,False,plasma,None,None,output,NaN,None,clearance_intrinsic,None,midazolam,NaN,38.700000,NaN,NaN,NaN,9.240000,3.772214,0.238760,liter / hour
184072,1,1826,-1,Test1,Test1,True,False,plasma,None,None,output,NaN,None,fraction_absorbed,None,midazolam,NaN,0.440000,NaN,NaN,NaN,0.170000,0.069402,0.386364,dimensionless
184098,1,1826,-1,Test1,Test1,True,False,plasma,None,po15,timecourse,0.17,hr,concentration,None,midazolam,NaN,0.000010,NaN,NaN,NaN,0.000005,0.000002,0.471287,gram / liter
184099,1,1826,-1,Test1,Test1,True,False,plasma,None,po15,timecourse,0.33,hr,concentration,None,midazolam,NaN,0.000132,NaN,NaN,NaN,0.000075,0.000031,0.566316,gram / liter
184100,1,1826,-1,Test1,Test1,True,False,plasma,None,po15,timecourse,0.75,hr,concentration,None,midazolam,NaN,0.000134,NaN,NaN,NaN,0.000030,0.000012,0.223951,gram / liter
184101,1,1826,-1,Test1,Test1,True,False,plasma,None,po15,timecourse,1.00,hr,concentration,None,midazolam,NaN,0.000097,NaN,NaN,NaN,0.000042,0.000017,0.437170,gram / liter
184102,1,1826,-1,Test1,Test1,True,False,plasma,None,po15,timecourse,1.50,hr,concentration,None,midazolam,NaN,0.000097,NaN,NaN,NaN,0.000053,0.000022,0.547883,gram / liter
184103,1,1826,-1,Test1,Test1,True,False,plasma,None,po15,timecourse,2.00,hr,concentration,None,midazolam,NaN,0.000068,NaN,NaN,NaN,0.000025,0.000010,0.370387,gram / liter
184104,1,1826,-1,Test1,Test1,True,False,plasma,None,po15,timecourse,2.50,hr,concentration,None,midazolam,NaN,0.000057,NaN,NaN,NaN,0.000012,0.000005,0.206021,gram / liter
184105,1,1826,-1,Test1,Test1,True,False,plasma,None,po15,timecourse,3.00,hr,concentration,None,midazolam,NaN,0.000046,NaN,NaN,NaN,0.000011,0.000004,0.234934,gram / liter
184106,1,1826,-1,Test1,Test1,True,False,plasma,None,po15,timecourse,4.00,hr,concentration,None,midazolam,NaN,0.000034,NaN,NaN,NaN,0.000011,0.000004,0.318302,gram / liter
184107,1,1826,-1,Test1,Test1,True,False,plasma,None,po15,timecourse,5.01,hr,concentration,None,midazolam,NaN,0.000023,NaN,NaN,NaN,0.000006,0.000002,0.245994,gram / liter
184108,1,1826,-1,Test1,Test1,True,False,plasma,None,po15,timecourse,6.00,hr,concentration,None,midazolam,NaN,0.000014,NaN,NaN,NaN,0.000004,0.000002,0.268551,gram / liter
184109,1,1826,-1,Test1,Test1,True,False,plasma,None,po15,timecourse,7.01,hr,concentration,None,midazolam,NaN,0.000011,NaN,NaN,NaN,0.000004,0.000002,0.345568,gram / liter
184110,0,1826,-1,Test1,Test1,True,False,plasma,None,iv,timecourse,0.00,hr,concentration,None,midazolam,NaN,0.000185,NaN,NaN,NaN,0.000023,0.000010,0.126198,gram / liter
184111,0,1826,-1,Test1,Test1,True,False,plasma,None,iv,timecourse,0.17,hr,concentration,None,midazolam,NaN,0.000144,NaN,NaN,NaN,0.000018,0.000007,0.126207,gram / liter
184112,0,1826,-1,Test1,Test1,True,False,plasma,None,iv,timecourse,0.33,hr,concentration,None,midazolam,NaN,0.000121,NaN,NaN,NaN,0.000021,0.000008,0.170746,gram / liter
184113,0,1826,-1,Test1,Test1,True,False,plasma,None,iv,timecourse,0.50,hr,concentration,None,midazolam,NaN,0.000106,NaN,NaN,NaN,0.000027,0.000011,0.253449,gram / liter
184114,0,1826,-1,Test1,Test1,True,False,plasma,None,iv,timecourse,0.75,hr,concentration,None,midazolam,NaN,0.000084,NaN,NaN,NaN,0.000010,0.000004,0.122627,gram / liter
184115,0,1826,-1,Test1,Test1,True,False,plasma,None,iv,timecourse,1.00,hr,concentration,None,midazolam,NaN,0.000077,NaN,NaN,NaN,0.000020,0.000008,0.259390,gram / liter
184116,0,1826,-1,Test1,Test1,True,False,plasma,None,iv,timecourse,1.50,hr,concentration,None,midazolam,NaN,0.000058,NaN,NaN,NaN,0.000009,0.000004,0.160776,gram / liter
184117,0,1826,-1,Test1,Test1,True,False,plasma,None,iv,timecourse,2.00,hr,concentration,None,midazolam,NaN,0.000044,NaN,NaN,NaN,0.000013,0.000005,0.302067,gram / liter
184118,0,1826,-1,Test1,Test1,True,False,plasma,None,iv,timecourse,3.00,hr,concentration,None,midazolam,NaN,0.000031,NaN,NaN,NaN,0.000010,0.000004,0.324525,gram / liter
184119,0,1826,-1,Test1,Test1,True,False,plasma,None,iv,timecourse,4.00,hr,concentration,None,midazolam,NaN,0.000021,NaN,NaN,NaN,0.000007,0.000003,0.328422,gram / liter
184120,0,1826,-1,Test1,Test1,True,False,plasma,None,iv,timecourse,5.00,hr,concentration,None,midazolam,NaN,0.000017,NaN,NaN,NaN,0.000008,0.000003,0.462537,gram / liter
184121,0,1826,-1,Test1,Test1,True,False,plasma,None,iv,timecourse,6.00,hr,concentration,None,midazolam,NaN,0.000014,NaN,NaN,NaN,0.000006,0.000002,0.422666,gram / liter
184122,0,1826,-1,Test1,Test1,True,False,plasma,None,iv,timecourse,7.00,hr,concentration,None,midazolam,NaN,0.000011,NaN,NaN,NaN,0.000003,0.000001,0.295669,gram / liter
184131,0,1826,-1,Test1,Test1,True,True,plasma,None,None,,7.00,hr,auc_end,None,midazolam,NaN,0.000282,NaN,NaN,NaN,NaN,NaN,NaN,gram * hour / liter
184132,0,1826,-1,Test1,Test1,True,True,plasma,None,None,,NaN,None,auc_inf,None,midazolam,NaN,0.000310,NaN,NaN,NaN,NaN,NaN,NaN,gram * hour / liter
184133,0,1826,-1,Test1,Test1,True,True,plasma,None,None,,NaN,None,clearance,None,midazolam,NaN,0.241684,NaN,NaN,NaN,NaN,NaN,NaN,liter / hour / kilogram
184134,0,1826,-1,Test1,Test1,True,True,plasma,None,None,,NaN,None,cmax,None,midazolam,NaN,0.000185,NaN,NaN,NaN,NaN,NaN,NaN,gram / liter
184135,0,1826,-1,Test1,Test1,True,True,plasma,None,None,,NaN,None,kel,None,midazolam,NaN,0.006201,NaN,NaN,NaN,NaN,NaN,NaN,1 / minute
184136,0,1826,-1,Test1,Test1,True,True,plasma,None,None,,NaN,None,thalf,None,midazolam,NaN,1.862878,NaN,NaN,NaN,NaN,NaN,NaN,hour
184137,0,1826,-1,Test1,Test1,True,True,plasma,None,None,,NaN,None,vd,None,midazolam,NaN,0.649543,NaN,NaN,NaN,NaN,NaN,NaN,liter / kilogram
184138,0,1826,-1,Test1,Test1,True,True,plasma,None,None,,NaN,None,vd_ss,None,midazolam,NaN,0.649739,NaN,NaN,NaN,NaN,NaN,NaN,liter / kilogram
184148,1,1826,-1,Test1,Test1,True,True,plasma,None,None,,7.01,hr,auc_end,None,midazolam,NaN,0.000343,NaN,NaN,NaN,NaN,NaN,NaN,gram * hour / liter
184149,1,1826,-1,Test1,Test1,True,True,plasma,None,None,,NaN,None,auc_inf,None,midazolam,NaN,0.000372,NaN,NaN,NaN,NaN,NaN,NaN,gram * hour / liter
184150,1,1826,-1,Test1,Test1,True,True,plasma,None,None,,NaN,None,clearance,None,midazolam,NaN,40.278043,NaN,NaN,NaN,NaN,NaN,NaN,liter / hour
184151,1,1826,-1,Test1,Test1,True,True,plasma,None,None,,NaN,None,cmax,None,midazolam,NaN,0.000134,NaN,NaN,NaN,NaN,NaN,NaN,gram / liter
184152,1,1826,-1,Test1,Test1,True,True,plasma,None,None,,NaN,None,kel,None,midazolam,NaN,0.006299,NaN,NaN,NaN,NaN,NaN,NaN,1 / minute
184153,1,1826,-1,Test1,Test1,True,True,plasma,None,None,,NaN,None,thalf,None,midazolam,NaN,1.833898,NaN,NaN,NaN,NaN,NaN,NaN,hour
184154,1,1826,-1,Test1,Test1,True,True,plasma,None,None,,NaN,None,tmax,None,midazolam,NaN,0.750000,NaN,NaN,NaN,NaN,NaN,NaN,hour
184155,1,1826,-1,Test1,Test1,True,True,plasma,None,None,,NaN,None,vd,None,midazolam,NaN,106.565845,NaN,NaN,NaN,NaN,NaN,NaN,liter

                                                 study_sid study_name  normed  \
output_pk intervention_pk group_pk individual_pk
183973    0               -1        7860             Test1      Test1    True
183974    0               -1        7860             Test1      Test1    True
183975    0               -1        7860             Test1      Test1    True
183976    0               -1        7860             Test1      Test1    True
183977    0               -1        7860             Test1      Test1    True
183978    1               -1        7860             Test1      Test1    True
183979    1               -1        7860             Test1      Test1    True
183980    1               -1        7860             Test1      Test1    True
183981    1               -1        7860             Test1      Test1    True
183982    1               -1        7860             Test1      Test1    True
183983    1               -1        7860             Test1      Test1    True
183984    2               -1        7860             Test1      Test1    True
183985    2               -1        7860             Test1      Test1    True
183986    2               -1        7860             Test1      Test1    True
183987    2               -1        7860             Test1      Test1    True
183988    2               -1        7860             Test1      Test1    True
183989    2               -1        7860             Test1      Test1    True
183990    0               -1        7861             Test1      Test1    True
183991    0               -1        7861             Test1      Test1    True
183992    0               -1        7861             Test1      Test1    True
183993    0               -1        7861             Test1      Test1    True
183994    0               -1        7861             Test1      Test1    True
183995    1               -1        7861             Test1      Test1    True
183996    1               -1        7861             Test1      Test1    True
183997    1               -1        7861             Test1      Test1    True
183998    1               -1        7861             Test1      Test1    True
183999    1               -1        7861             Test1      Test1    True
184000    1               -1        7861             Test1      Test1    True
184001    0               -1        7862             Test1      Test1    True
184002    0               -1        7862             Test1      Test1    True
184003    0               -1        7862             Test1      Test1    True
184004    0               -1        7862             Test1      Test1    True
184005    0               -1        7862             Test1      Test1    True
184006    1               -1        7862             Test1      Test1    True
184007    1               -1        7862             Test1      Test1    True
184008    1               -1        7862             Test1      Test1    True
184009    1               -1        7862             Test1      Test1    True
184010    1               -1        7862             Test1      Test1    True
184011    1               -1        7862             Test1      Test1    True
184012    2               -1        7862             Test1      Test1    True
184013    2               -1        7862             Test1      Test1    True
184014    2               -1        7862             Test1      Test1    True
184015    2               -1        7862             Test1      Test1    True
184016    2               -1        7862             Test1      Test1    True
184017    2               -1        7862             Test1      Test1    True
184018    0               -1        7863             Test1      Test1    True
184019    0               -1        7863             Test1      Test1    True
184020    0               -1        7863             Test1      Test1    True
184021    0               -1        7863             Test1      Test1    True
184022    0               -1        7863             Test1      Test1    True
184023    1               -1        7863             Test1      Test1    True
184024    1               -1        7863             Test1      Test1    True
184025    1               -1        7863             Test1      Test1    True
184026    1               -1        7863             Test1      Test1    True
184027    1               -1        7863             Test1      Test1    True
184028    1               -1        7863             Test1      Test1    True
184029    0               -1        7864             Test1      Test1    True
184030    0               -1        7864             Test1      Test1    True
184031    0               -1        7864             Test1      Test1    True
184032    0               -1        7864             Test1      Test1    True
184033    0               -1        7864             Test1      Test1    True
184034    1               -1        7864             Test1      Test1    True
184035    1               -1        7864             Test1      Test1    True
184036    1               -1        7864             Test1      Test1    True
184037    1               -1        7864             Test1      Test1    True
184038    1               -1        7864             Test1      Test1    True
184039    1               -1        7864             Test1      Test1    True
184040    0               -1        7865             Test1      Test1    True
184041    0               -1        7865             Test1      Test1    True
184042    0               -1        7865             Test1      Test1    True
184043    0               -1        7865             Test1      Test1    True
184044    0               -1        7865             Test1      Test1    True
184045    1               -1        7865             Test1      Test1    True
184046    1               -1        7865             Test1      Test1    True
184047    1               -1        7865             Test1      Test1    True
184048    1               -1        7865             Test1      Test1    True
184049    1               -1        7865             Test1      Test1    True
184050    1               -1        7865             Test1      Test1    True
184062    0                1826    -1                Test1      Test1    True
184063    0                1826    -1                Test1      Test1    True
184064    0                1826    -1                Test1      Test1    True
184065    0                1826    -1                Test1      Test1    True
184066    0                1826    -1                Test1      Test1    True
184067    1                1826    -1                Test1      Test1    True
184068    1                1826    -1                Test1      Test1    True
184069    1                1826    -1                Test1      Test1    True
184070    1                1826    -1                Test1      Test1    True
184071    1                1826    -1                Test1      Test1    True
184072    1                1826    -1                Test1      Test1    True
184098    1                1826    -1                Test1      Test1    True
184099    1                1826    -1                Test1      Test1    True
184100    1                1826    -1                Test1      Test1    True
184101    1                1826    -1                Test1      Test1    True
184102    1                1826    -1                Test1      Test1    True
184103    1                1826    -1                Test1      Test1    True
184104    1                1826    -1                Test1      Test1    True
184105    1                1826    -1                Test1      Test1    True
184106    1                1826    -1                Test1      Test1    True
184107    1                1826    -1                Test1      Test1    True
184108    1                1826    -1                Test1      Test1    True
184109    1                1826    -1                Test1      Test1    True
184110    0                1826    -1                Test1      Test1    True
184111    0                1826    -1                Test1      Test1    True
184112    0                1826    -1                Test1      Test1    True
184113    0                1826    -1                Test1      Test1    True
184114    0                1826    -1                Test1      Test1    True
184115    0                1826    -1                Test1      Test1    True
184116    0                1826    -1                Test1      Test1    True
184117    0                1826    -1                Test1      Test1    True
184118    0                1826    -1                Test1      Test1    True
184119    0                1826    -1                Test1      Test1    True
184120    0                1826    -1                Test1      Test1    True
184121    0                1826    -1                Test1      Test1    True
184122    0                1826    -1                Test1      Test1    True
184131    0                1826    -1                Test1      Test1    True
184132    0                1826    -1                Test1      Test1    True
184133    0                1826    -1                Test1      Test1    True
184134    0                1826    -1                Test1      Test1    True
184135    0                1826    -1                Test1      Test1    True
184136    0                1826    -1                Test1      Test1    True
184137    0                1826    -1                Test1      Test1    True
184138    0                1826    -1                Test1      Test1    True
184148    1                1826    -1                Test1      Test1    True
184149    1                1826    -1                Test1      Test1    True
184150    1                1826    -1                Test1      Test1    True
184151    1                1826    -1                Test1      Test1    True
184152    1                1826    -1                Test1      Test1    True
184153    1                1826    -1                Test1      Test1    True
184154    1                1826    -1                Test1      Test1    True
184155    1                1826    -1                Test1      Test1    True
184156    1                1826    -1                Test1      Test1    True

                                                  calculated  tissue method  \
output_pk intervention_pk group_pk individual_pk
183973    0               -1        7860               False  plasma   None
183974    0               -1        7860               False  plasma   None
183975    0               -1        7860               False  plasma   None
183976    0               -1        7860               False  plasma   None
183977    0               -1        7860               False  plasma   None
183978    1               -1        7860               False  plasma   None
183979    1               -1        7860               False  plasma   None
183980    1               -1        7860               False  plasma   None
183981    1               -1        7860               False  plasma   None
183982    1               -1        7860               False  plasma   None
183983    1               -1        7860               False  plasma   None
183984    2               -1        7860               False  plasma   None
183985    2               -1        7860               False  plasma   None
183986    2               -1        7860               False  plasma   None
183987    2               -1        7860               False  plasma   None
183988    2               -1        7860               False  plasma   None
183989    2               -1        7860               False  plasma   None
183990    0               -1        7861               False  plasma   None
183991    0               -1        7861               False  plasma   None
183992    0               -1        7861               False  plasma   None
183993    0               -1        7861               False  plasma   None
183994    0               -1        7861               False  plasma   None
183995    1               -1        7861               False  plasma   None
183996    1               -1        7861               False  plasma   None
183997    1               -1        7861               False  plasma   None
183998    1               -1        7861               False  plasma   None
183999    1               -1        7861               False  plasma   None
184000    1               -1        7861               False  plasma   None
184001    0               -1        7862               False  plasma   None
184002    0               -1        7862               False  plasma   None
184003    0               -1        7862               False  plasma   None
184004    0               -1        7862               False  plasma   None
184005    0               -1        7862               False  plasma   None
184006    1               -1        7862               False  plasma   None
184007    1               -1        7862               False  plasma   None
184008    1               -1        7862               False  plasma   None
184009    1               -1        7862               False  plasma   None
184010    1               -1        7862               False  plasma   None
184011    1               -1        7862               False  plasma   None
184012    2               -1        7862               False  plasma   None
184013    2               -1        7862               False  plasma   None
184014    2               -1        7862               False  plasma   None
184015    2               -1        7862               False  plasma   None
184016    2               -1        7862               False  plasma   None
184017    2               -1        7862               False  plasma   None
184018    0               -1        7863               False  plasma   None
184019    0               -1        7863               False  plasma   None
184020    0               -1        7863               False  plasma   None
184021    0               -1        7863               False  plasma   None
184022    0               -1        7863               False  plasma   None
184023    1               -1        7863               False  plasma   None
184024    1               -1        7863               False  plasma   None
184025    1               -1        7863               False  plasma   None
184026    1               -1        7863               False  plasma   None
184027    1               -1        7863               False  plasma   None
184028    1               -1        7863               False  plasma   None
184029    0               -1        7864               False  plasma   None
184030    0               -1        7864               False  plasma   None
184031    0               -1        7864               False  plasma   None
184032    0               -1        7864               False  plasma   None
184033    0               -1        7864               False  plasma   None
184034    1               -1        7864               False  plasma   None
184035    1               -1        7864               False  plasma   None
184036    1               -1        7864               False  plasma   None
184037    1               -1        7864               False  plasma   None
184038    1               -1        7864               False  plasma   None
184039    1               -1        7864               False  plasma   None
184040    0               -1        7865               False  plasma   None
184041    0               -1        7865               False  plasma   None
184042    0               -1        7865               False  plasma   None
184043    0               -1        7865               False  plasma   None
184044    0               -1        7865               False  plasma   None
184045    1               -1        7865               False  plasma   None
184046    1               -1        7865               False  plasma   None
184047    1               -1        7865               False  plasma   None
184048    1               -1        7865               False  plasma   None
184049    1               -1        7865               False  plasma   None
184050    1               -1        7865               False  plasma   None
184062    0                1826    -1                  False  plasma   None
184063    0                1826    -1                  False  plasma   None
184064    0                1826    -1                  False  plasma   None
184065    0                1826    -1                  False  plasma   None
184066    0                1826    -1                  False  plasma   None
184067    1                1826    -1                  False  plasma   None
184068    1                1826    -1                  False  plasma   None
184069    1                1826    -1                  False  plasma   None
184070    1                1826    -1                  False  plasma   None
184071    1                1826    -1                  False  plasma   None
184072    1                1826    -1                  False  plasma   None
184098    1                1826    -1                  False  plasma   None
184099    1                1826    -1                  False  plasma   None
184100    1                1826    -1                  False  plasma   None
184101    1                1826    -1                  False  plasma   None
184102    1                1826    -1                  False  plasma   None
184103    1                1826    -1                  False  plasma   None
184104    1                1826    -1                  False  plasma   None
184105    1                1826    -1                  False  plasma   None
184106    1                1826    -1                  False  plasma   None
184107    1                1826    -1                  False  plasma   None
184108    1                1826    -1                  False  plasma   None
184109    1                1826    -1                  False  plasma   None
184110    0                1826    -1                  False  plasma   None
184111    0                1826    -1                  False  plasma   None
184112    0                1826    -1                  False  plasma   None
184113    0                1826    -1                  False  plasma   None
184114    0                1826    -1                  False  plasma   None
184115    0                1826    -1                  False  plasma   None
184116    0                1826    -1                  False  plasma   None
184117    0                1826    -1                  False  plasma   None
184118    0                1826    -1                  False  plasma   None
184119    0                1826    -1                  False  plasma   None
184120    0                1826    -1                  False  plasma   None
184121    0                1826    -1                  False  plasma   None
184122    0                1826    -1                  False  plasma   None
184131    0                1826    -1                   True  plasma   None
184132    0                1826    -1                   True  plasma   None
184133    0                1826    -1                   True  plasma   None
184134    0                1826    -1                   True  plasma   None
184135    0                1826    -1                   True  plasma   None
184136    0                1826    -1                   True  plasma   None
184137    0                1826    -1                   True  plasma   None
184138    0                1826    -1                   True  plasma   None
184148    1                1826    -1                   True  plasma   None
184149    1                1826    -1                   True  plasma   None
184150    1                1826    -1                   True  plasma   None

,,,,study_sid,study_name,output_pk,subset_name,normed,tissue,tissue_label,method,method_label,label,time,time_unit,measurement_type,measurement_type_label,choice,choice_label,substance,substance_label,value,mean,median,min,max,sd,se,cv,unit
subset_pk,intervention_pk,group_pk,individual_pk,,,,,,,,,,,,,,,,,,,,,,,,,,,
3948,0,1826,-1,Test1,Test1,"[184121, 184122, 184110, 184111, 184112, 18411...",iv,True,plasma,plasma,None,None,iv,"[6.0, 7.0, 0.0, 0.17, 0.33, 0.5, 0.75, 1.0, 1....",hr,concentration,concentration,None,None,midazolam,midazolam,None,"[1.4030000000000001e-05, 1.0620000000000002e-0...",None,None,None,"[5.930000000000001e-06, 3.140000000000001e-06,...","[2.420912362450708e-06, 1.2818996320565302e-06...","[0.4226657163221668, 0.2956685499058381, 0.126...",gram / liter
3949,1,1826,-1,Test1,Test1,"[184108, 184109, 184098, 184099, 184100, 18410...",po15,True,plasma,plasma,None,None,po15,"[6.0, 7.01, 0.17, 0.33, 0.75, 1.0, 1.5, 2.0, 2...",hr,concentration,concentration,None,None,midazolam,midazolam,None,"[1.4150000000000003e-05, 1.1170000000000001e-0...",None,None,None,"[3.8000000000000005e-06, 3.86e-06, 4.76e-06, 7...","[1.5513435037626797e-06, 1.5758384011905116e-0...","[0.2685512367491166, 0.34556848701880033, 0.47...",gram / liter

                                                 study_sid study_name  \
subset_pk intervention_pk group_pk individual_pk
3948      0               1826     -1                Test1      Test1
3949      1               1826     -1                Test1      Test1

                                                                                          output_pk  \
subset_pk intervention_pk group_pk individual_pk
3948      0               1826     -1             [184121, 184122, 184110, 184111, 184112, 18411...
3949      1               1826     -1             [184108, 184109, 184098, 184099, 184100, 18410...

                                                 subset_name  normed  tissue  \
subset_pk intervention_pk group_pk individual_pk
3948      0               1826     -1                     iv    True  plasma
3949      1               1826     -1                   po15    True  plasma

                                                 tissue_label method  \
subset_pk intervention_pk group_pk individual_pk
3948      0               1826     -1                  plasma   None
3949      1               1826     -1                  plasma   None

                                                 method_label label  \
subset_pk intervention_pk group_pk individual_pk
3948      0               1826     -1                    None    iv
3949      1               1826     -1                    None  po15

                                                                                               time  \
subset_pk intervention_pk group_pk individual_pk
3948      0               1826     -1             [6.0, 7.0, 0.0, 0.17, 0.33, 0.5, 0.75, 1.0, 1....
3949      1               1826     -1             [6.0, 7.01, 0.17, 0.33, 0.75, 1.0, 1.5, 2.0, 2...

                                                 time_unit measurement_type  \
subset_pk intervention_pk group_pk individual_pk
3948      0               1826     -1                   hr    concentration
3949      1               1826     -1                   hr    concentration

                                                 measurement_type_label  \
subset_pk intervention_pk group_pk individual_pk
3948      0               1826     -1                     concentration
3949      1               1826     -1                     concentration

                                                 choice choice_label  \
subset_pk intervention_pk group_pk individual_pk
3948      0               1826     -1              None         None
3949      1               1826     -1              None         None

                                                  substance substance_label  \
subset_pk intervention_pk group_pk individual_pk
3948      0               1826     -1             midazolam       midazolam
3949      1               1826     -1             midazolam       midazolam

                                                 value  \
subset_pk intervention_pk group_pk individual_pk
3948      0               1826     -1             None
3949      1               1826     -1             None

                                                                                               mean  \
subset_pk intervention_pk group_pk individual_pk
3948      0               1826     -1             [1.4030000000000001e-05, 1.0620000000000002e-0...
3949      1               1826     -1             [1.4150000000000003e-05, 1.1170000000000001e-0...

                                                 median   min   max  \
subset_pk intervention_pk group_pk individual_pk
3948      0               1826     -1              None  None  None
3949      1               1826     -1              None  None  None

                                                                                                 sd  \
subset_pk intervention_pk group_pk individual_pk
3948      0               1826     -1             [5.930000000000001e-06, 3.140000000000001e-06,...
3949      1               1826     -1             [3.8000000000000005e-06, 3.86e-06, 4.76e-06, 7...

                                                                                                 se  \
subset_pk intervention_pk group_pk individual_pk
3948      0               1826     -1             [2.420912362450708e-06, 1.2818996320565302e-06...
3949      1               1826     -1             [1.5513435037626797e-06, 1.5758384011905116e-0...

                                                                                                 cv  \
subset_pk intervention_pk group_pk individual_pk
3948      0               1826     -1             [0.4226657163221668, 0.2956685499058381, 0.126...
3949      1               1826     -1             [0.2685512367491166, 0.34556848701880033, 0.47...

                                                          unit
subset_pk intervention_pk group_pk individual_pk
3948      0               1826     -1             gram / liter
3949      1               1826     -1             gram / liter

In [ ]:
data.timecourses

In [ ]:
data.timecourses