In [1]:
%load_ext autoreload
%autoreload 2

import pandas as pd
from IPython.display import display

from pkdb_analysis import PKData, PKFilter
from pkdb_analysis.tests.constants import TEST_HDF5

# Working with PK-DB data
To easily work with PK-DB data we provide the `pkdb_analysis` python library.
These includes helper functions for querying data and filter existing data sets. In the following we provide an overview over the typical functionality when working with PK-DB data.

The main class to work with is `PKData`. It is possible to directly query the database or to load data from file.

## Load data from file
PKData can be serialized to HDF5 files. In the following we will load the test data set and print an overview.

In [2]:
from pkdb_analysis import PKData, PKFilter
from pkdb_analysis.tests.constants import TEST_HDF5

data = PKData.from_hdf5(TEST_HDF5)
print(data)

INFO Note: NumExpr detected 32 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO NumExpr defaulting to 8 threads.

------------------------------
PKData (140432779705360)
------------------------------
studies             4
groups              8  (   86)
individuals       246  ( 3144)
interventions      18  (   18)
outputs          1064  ( 1106)
timecourses        40  (   46)
------------------------------

## Load data from database
Alternatively data can be loaded from the database using the `PKDB.query()` function.
This is documented in the `Querying PK-DB` section.

## Accessing groups, individuals, interventions, outputs and timecourses
All PKData consists of consistent information on:
- `studies`: PK-DB studies, uniquely identified via a `study_sid`
- `groups`: groups, uniquely identified via `group_pk`
- `individuals`: individuals, uniquely identified via `individual_pk`
- `interventions`: interventions, uniquely identified via `intervention_pk`
- `outputs`: outputs, uniquely identified via `output_pk`
- `timecourses`: groups, uniquely identified via `timecourse_pk`

The `print` function provides a simple overview over the content

In [3]:
print(data)

------------------------------
PKData (140432779705360)
------------------------------
studies             4
groups              8  (   86)
individuals       246  ( 3144)
interventions      18  (   18)
outputs          1064  ( 1106)
timecourses        40  (   46)
------------------------------

We can access the information via the respective fields, e.g., groups via `data.groups` or the multi-index data via `data.groups_mi`.

In [4]:
data.groups

,study_sid,study_name,group_pk,group_name,group_count,group_parent_pk,characteristica_pk,count,measurement_type,choice,substance,value,mean,median,min,max,sd,se,cv,unit
0,PKDB99997,Test3,26,all,2,-1,1068,2,abstinence,None,cocoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
1,PKDB99997,Test3,26,all,2,-1,1067,2,abstinence,None,tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
2,PKDB99997,Test3,26,all,2,-1,1066,2,abstinence,None,coffee,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
3,PKDB99997,Test3,26,all,2,-1,1065,2,species,homo sapiens,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
4,PKDB99999,Test1,20,all,6,-1,481,6,species,homo sapiens,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,PKDB99998,Test2,25,80-90,10,21,523,40,medication,N,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
82,PKDB99998,Test2,25,80-90,10,21,584,10,gfr,None,None,NaN,36.99422,NaN,NaN,NaN,10.982659,NaN,NaN,milliliter / meter ** 2 / minute
83,PKDB99998,Test2,25,80-90,10,21,526,40,ethnicity,caucasian,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
84,PKDB99998,Test2,25,80-90,10,21,527,38,smoking,N,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
85,PKDB99998,Test2,25,80-90,10,21,528,2,smoking,Y,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None

In [5]:
data.groups_mi

                             study_sid study_name group_name  group_count  \
group_pk characteristica_pk
20       481                 PKDB99999      Test1        all            6
         482                 PKDB99999      Test1        all            6
         483                 PKDB99999      Test1        all            6
         484                 PKDB99999      Test1        all            6
         485                 PKDB99999      Test1        all            6
...                                ...        ...        ...          ...
27       1086                PKDB99996      Test4        all           16
         1087                PKDB99996      Test4        all           16
         1088                PKDB99996      Test4        all           16
         1089                PKDB99996      Test4        all           16
         1090                PKDB99996      Test4        all           16

                             group_parent_pk  count measurement_type  \
group_pk characteristica_pk
20       481                              -1      6          species
         482                              -1      6          healthy
         483                              -1      1          smoking
         484                              -1      5          smoking
         485                              -1      6              age
...                                      ...    ...              ...
27       1086                             -1     16          alcohol
         1087                             -1     16           weight
         1088                             -1     16              age
         1089                             -1     16        ethnicity
         1090                             -1     16   overnight fast

                                   choice substance  value  mean  median  \
group_pk characteristica_pk
20       481                 homo sapiens      None    NaN   NaN     NaN
         482                            Y      None    NaN   NaN     NaN
         483                            Y      None    NaN   NaN     NaN
         484                            N      None    NaN   NaN     NaN
         485                         None      None    NaN   NaN     NaN
...                                   ...       ...    ...   ...     ...
27       1086                           N      None    NaN   NaN     NaN
         1087                        None      None    NaN  76.7     NaN
         1088                        None      None    NaN  27.1     NaN
         1089                          NR      None    NaN   NaN     NaN
         1090                           Y      None    NaN   NaN     NaN

                              min   max   sd  se  cv      unit
group_pk characteristica_pk
20       481                  NaN   NaN  NaN NaN NaN      None
         482                  NaN   NaN  NaN NaN NaN      None
         483                  NaN   NaN  NaN NaN NaN      None
         484                  NaN   NaN  NaN NaN NaN      None
         485                 25.0  37.0  NaN NaN NaN        yr
...                           ...   ...  ...  ..  ..       ...
27       1086                 NaN   NaN  NaN NaN NaN      None
         1087                 NaN   NaN  6.8 NaN NaN  kilogram
         1088                 NaN   NaN  3.1 NaN NaN        yr
         1089                 NaN   NaN  NaN NaN NaN      None
         1090                 NaN   NaN  NaN NaN NaN      None

[86 rows x 18 columns]

To access the number of items use the `*_count`.

In [6]:
print(f"Number of groups: {data.groups_count}")

Number of groups: 8

The `groups`, `individuals`, `interventions`, `outputs` and `timecourses` are `pandas.DataFrame` instances, so all the classical pandas operations can be applied on the data.
For instance to access a single `group` use logical indexing by the `group_pk` field.
E.g. to get the group `20` use

In [7]:
data.groups[data.groups.group_pk==20]

,study_sid,study_name,group_pk,group_name,group_count,group_parent_pk,characteristica_pk,count,measurement_type,choice,substance,value,mean,median,min,max,sd,se,cv,unit
4,PKDB99999,Test1,20,all,6,-1,481,6,species,homo sapiens,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
5,PKDB99999,Test1,20,all,6,-1,482,6,healthy,Y,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
6,PKDB99999,Test1,20,all,6,-1,483,1,smoking,Y,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
7,PKDB99999,Test1,20,all,6,-1,484,5,smoking,N,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
8,PKDB99999,Test1,20,all,6,-1,485,6,age,None,None,NaN,NaN,NaN,25.0,37.0,NaN,NaN,NaN,yr
9,PKDB99999,Test1,20,all,6,-1,486,6,overnight fast,Y,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None

In the group tables multiple rows exist which belong to a single group! This is important to understand filtering of the data later on. For instance in this example the information on `species`, `healthy`, `smoking`, `age` and `overnight_fast` are all separate rows in the `groups` table, but belong to a single row.

When looking at the multi-index table this becomes more clear. We now get the group 20 form the `groups_mi`. We can simply use the `.loc` to lookup the group by `pk`

In [8]:
data.groups_mi.loc[20]

,study_sid,study_name,group_name,group_count,group_parent_pk,count,measurement_type,choice,substance,value,mean,median,min,max,sd,se,cv,unit
characteristica_pk,,,,,,,,,,,,,,,,,,
481,PKDB99999,Test1,all,6,-1,6,species,homo sapiens,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
482,PKDB99999,Test1,all,6,-1,6,healthy,Y,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
483,PKDB99999,Test1,all,6,-1,1,smoking,Y,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
484,PKDB99999,Test1,all,6,-1,5,smoking,N,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
485,PKDB99999,Test1,all,6,-1,6,age,None,None,NaN,NaN,NaN,25.0,37.0,NaN,NaN,NaN,yr
486,PKDB99999,Test1,all,6,-1,6,overnight fast,Y,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None

In a similar manner we can explore the other information, i.e. `individuals`, `interventions`, `outputs` and `timecourses`.

In [9]:
data.individuals_mi

                                  study_sid study_name individual_name  \
individual_pk characteristica_pk
39            481                 PKDB99999      Test1              WS
              482                 PKDB99999      Test1              WS
              483                 PKDB99999      Test1              WS
              484                 PKDB99999      Test1              WS
              486                 PKDB99999      Test1              WS
...                                     ...        ...             ...
283           1068                PKDB99997      Test3            H.C.
284           1065                PKDB99997      Test3            F.M.
              1066                PKDB99997      Test3            F.M.
              1067                PKDB99997      Test3            F.M.
              1068                PKDB99997      Test3            F.M.

                                  individual_group_pk  count measurement_type  \
individual_pk characteristica_pk
39            481                                  20      6          species
              482                                  20      6          healthy
              483                                  20      1          smoking
              484                                  20      5          smoking
              486                                  20      6   overnight fast
...                                               ...    ...              ...
283           1068                                 26      2       abstinence
284           1065                                 26      2          species
              1066                                 26      2       abstinence
              1067                                 26      2       abstinence
              1068                                 26      2       abstinence

                                        choice substance  value  mean  median  \
individual_pk characteristica_pk
39            481                 homo sapiens      None    NaN   NaN     NaN
              482                            Y      None    NaN   NaN     NaN
              483                            Y      None    NaN   NaN     NaN
              484                            N      None    NaN   NaN     NaN
              486                            Y      None    NaN   NaN     NaN
...                                        ...       ...    ...   ...     ...
283           1068                        None     cocoa    NaN   NaN     NaN
284           1065                homo sapiens      None    NaN   NaN     NaN
              1066                        None    coffee    NaN   NaN     NaN
              1067                        None       tea    NaN   NaN     NaN
              1068                        None     cocoa    NaN   NaN     NaN

                                  min  max  sd  se  cv  unit
individual_pk characteristica_pk
39            481                 NaN  NaN NaN NaN NaN  None
              482                 NaN  NaN NaN NaN NaN  None
              483                 NaN  NaN NaN NaN NaN  None
              484                 NaN  NaN NaN NaN NaN  None
              486                 NaN  NaN NaN NaN NaN  None
...                               ...  ...  ..  ..  ..   ...
283           1068                NaN  NaN NaN NaN NaN  None
284           1065                NaN  NaN NaN NaN NaN  None
              1066                NaN  NaN NaN NaN NaN  None
              1067                NaN  NaN NaN NaN NaN  None
              1068                NaN  NaN NaN NaN NaN  None

[3144 rows x 17 columns]

In [10]:
data.interventions_mi

,study_sid,study_name,raw_pk,normed,name,route,form,application,time,time_unit,...,substance,value,mean,median,min,max,sd,se,cv,unit
intervention_pk,,,,,,,,,,,,,,,,,,,,,
91,PKDB99999,Test1,-1,False,po75,oral,tablet,single dose,0.0,hr,...,midazolam,7.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mg
92,PKDB99999,Test1,-1,False,po15,oral,tablet,single dose,0.0,hr,...,midazolam,15.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mg
93,PKDB99999,Test1,91,True,po75,oral,tablet,single dose,0.0,hr,...,midazolam,0.007500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gram
94,PKDB99999,Test1,92,True,po15,oral,tablet,single dose,0.0,hr,...,midazolam,0.015000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gram
95,PKDB99999,Test1,-1,False,iv,iv,solution,single dose,0.0,hr,...,midazolam,0.075000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mg/kg
96,PKDB99999,Test1,95,True,iv,iv,solution,single dose,0.0,hr,...,midazolam,0.000075,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gram / kilogram
97,PKDB99998,Test2,-1,False,paracetamol1000mg_iv,iv,solution,constant infusion,0.0,min,...,paracetamol,1000.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mg
98,PKDB99998,Test2,97,True,paracetamol1000mg_iv,iv,solution,constant infusion,0.0,min,...,paracetamol,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gram
99,PKDB99997,Test3,-1,False,theobromine,oral,None,None,0.0,hr,...,theobromine,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,g
100,PKDB99997,Test3,99,True,theobromine,oral,None,None,0.0,hr,...,theobromine,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gram
101,PKDB99997,Test3,-1,False,theophylline,oral,None,None,0.0,hr,...,theophylline,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,g
102,PKDB99997,Test3,101,True,theophylline,oral,None,None,0.0,hr,...,theophylline,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gram
103,PKDB99997,Test3,-1,False,caffeine,oral,None,None,0.0,hr,...,caffeine,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,g
104,PKDB99997,Test3,103,True,caffeine,oral,None,None,0.0,hr,...,caffeine,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gram
105,PKDB99996,Test4,-1,False,Dcaf,oral,tablet,single dose,0.0,hr,...,caffeine,200.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mg
106,PKDB99996,Test4,105,True,Dcaf,oral,tablet,single dose,0.0,hr,...,caffeine,0.200000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gram
107,PKDB99996,Test4,-1,False,Dlom,oral,capsule,multiple dose,NaN,None,...,lomefloxacin,400.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mg
108,PKDB99996,Test4,107,True,Dlom,oral,capsule,multiple dose,NaN,None,...,lomefloxacin,0.400000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gram

In [11]:
data.outputs_mi

                                                  study_sid study_name  \
output_pk intervention_pk group_pk individual_pk
1409      96              -1        39            PKDB99999      Test1
1410      96              -1        39            PKDB99999      Test1
1411      96              -1        39            PKDB99999      Test1
1412      96              -1        39            PKDB99999      Test1
1413      96              -1        39            PKDB99999      Test1
...                                                     ...        ...
2604      108              27      -1             PKDB99996      Test4
2605      106              27      -1             PKDB99996      Test4
          108              27      -1             PKDB99996      Test4
2606      106              27      -1             PKDB99996      Test4
          108              27      -1             PKDB99996      Test4

                                                  normed  calculated  tissue  \
output_pk intervention_pk group_pk individual_pk
1409      96              -1        39             False       False  plasma
1410      96              -1        39             False       False  plasma
1411      96              -1        39             False       False  plasma
1412      96              -1        39             False       False  plasma
1413      96              -1        39             False       False  plasma
...                                                  ...         ...     ...
2604      108              27      -1               True        True  plasma
2605      106              27      -1               True        True  plasma
          108              27      -1               True        True  plasma
2606      106              27      -1               True        True  plasma
          108              27      -1               True        True  plasma

                                                  time time_unit  \
output_pk intervention_pk group_pk individual_pk
1409      96              -1        39             NaN      None
1410      96              -1        39             NaN      None
1411      96              -1        39             NaN      None
1412      96              -1        39             NaN      None
1413      96              -1        39             NaN      None
...                                                ...       ...
2604      108              27      -1              NaN      None
2605      106              27      -1              NaN      None
          108              27      -1              NaN      None
2606      106              27      -1              NaN      None
          108              27      -1              NaN      None

                                                   measurement_type choice  \
output_pk intervention_pk group_pk individual_pk
1409      96              -1        39                        thalf   None
1410      96              -1        39                           vd   None
1411      96              -1        39                    clearance   None
1412      96              -1        39            clearance_unbound   None
1413      96              -1        39               plasma_binding   None
...                                                             ...    ...
2604      108              27      -1                         thalf   None
2605      106              27      -1                            vd   None
          108              27      -1                            vd   None
2606      106              27      -1                          tmax   None
          108              27      -1                          tmax   None

                                                     substance    value  \
output_pk intervention_pk group_pk individual_pk
1409      96              -1        39               midazolam     2.30
1410      96              -1        39               midazolam     0.71
1411      96              -1        39               midazolam   292.00
1412      96              -1        39               midazolam  5840.00
1413      96              -1        39               midazolam    95.00
...                                                        ...      ...
2604      108              27      -1             paraxanthine      NaN
2605      106              27      -1             paraxanthine      NaN
          108              27      -1             paraxanthine      NaN
2606      106              27      -1             paraxanthine      NaN
          108              27      -1             paraxanthine      NaN

                                                   mean  median  min  max  sd  \
output_pk intervention_pk group_pk individual_pk
1409      96              -1        39              NaN     NaN  NaN  NaN NaN
1410      96              -1        39              NaN     NaN  NaN  NaN NaN
1411      96              -1        39              NaN     NaN  NaN  NaN NaN
1412      96              -1        39              NaN     NaN  NaN  NaN NaN
1413      96              -1        39              NaN     NaN  NaN  NaN NaN
...                                                 ...     ...  ...  ...  ..
2604      108              27      -1              9.36     NaN  NaN  NaN NaN
2605      106              27      -1             90.30     NaN  NaN  NaN NaN
          108              27      -1             90.30     NaN  NaN  NaN NaN
2606      106              27      -1              6.00     NaN  NaN  NaN NaN
          108              27      -1              6.00     NaN  NaN  NaN NaN

                                                  se  cv     unit
output_pk intervention_pk group_pk individual_pk
1409      96              -1        39           NaN NaN       hr
1410      96              -1        39           NaN NaN     l/kg
1411      96              -1        39           NaN NaN   ml/min
1412      96              -1        39           NaN NaN   ml/min
1413      96              -1        39           NaN NaN  percent
...                                               ..  ..      ...
2604      108              27      -1            NaN NaN     hour
2605      106              27      -1            NaN NaN    liter
          108              27      -1            NaN NaN    liter
2606      106              27      -1            NaN NaN     hour
          108              27      -1            NaN NaN     hour

[1106 rows x 19 columns]

In [12]:
data.timecourses_mi

                                                      study_sid study_name  \
timecourse_pk intervention_pk group_pk individual_pk
67            96              20       -1             PKDB99999      Test1
68            94              20       -1             PKDB99999      Test1
69            96              20       -1             PKDB99999      Test1
70            94              20       -1             PKDB99999      Test1
71            98              22       -1             PKDB99998      Test2
72            98              22       -1             PKDB99998      Test2
73            98              22       -1             PKDB99998      Test2
74            98              23       -1             PKDB99998      Test2
75            98              23       -1             PKDB99998      Test2
76            98              23       -1             PKDB99998      Test2
77            98              24       -1             PKDB99998      Test2
78            98              24       -1             PKDB99998      Test2
79            98              24       -1             PKDB99998      Test2
80            98              25       -1             PKDB99998      Test2
81            98              25       -1             PKDB99998      Test2
82            98              25       -1             PKDB99998      Test2
83            98              22       -1             PKDB99998      Test2
84            98              22       -1             PKDB99998      Test2
85            98              22       -1             PKDB99998      Test2
86            98              23       -1             PKDB99998      Test2
87            98              23       -1             PKDB99998      Test2
88            98              23       -1             PKDB99998      Test2
89            98              24       -1             PKDB99998      Test2
90            98              24       -1             PKDB99998      Test2
91            98              24       -1             PKDB99998      Test2
92            98              25       -1             PKDB99998      Test2
93            98              25       -1             PKDB99998      Test2
94            98              25       -1             PKDB99998      Test2
95            106             27       -1             PKDB99996      Test4
96            106             27       -1             PKDB99996      Test4
              108             27       -1             PKDB99996      Test4
97            106             27       -1             PKDB99996      Test4
98            106             27       -1             PKDB99996      Test4
              108             27       -1             PKDB99996      Test4
99            106             27       -1             PKDB99996      Test4
100           106             27       -1             PKDB99996      Test4
              108             27       -1             PKDB99996      Test4
101           106             27       -1             PKDB99996      Test4
102           106             27       -1             PKDB99996      Test4
              108             27       -1             PKDB99996      Test4
103           106             27       -1             PKDB99996      Test4
104           106             27       -1             PKDB99996      Test4
              108             27       -1             PKDB99996      Test4
105           106             27       -1             PKDB99996      Test4
106           106             27       -1             PKDB99996      Test4
              108             27       -1             PKDB99996      Test4

                                                      normed  tissue  \
timecourse_pk intervention_pk group_pk individual_pk
67            96              20       -1              False  plasma
68            94              20       -1              False  plasma
69            96              20       -1               True  plasma
70            94              20       -1               True  plasma
71            98              22       -1              False  plasma
72            98              22       -1              False  plasma
73            98              22       -1              False  plasma
74            98              23       -1              False  plasma
75            98              23       -1              False  plasma
76            98              23       -1              False  plasma
77            98              24       -1              False  plasma
78            98              24       -1              False  plasma
79            98              24       -1              False  plasma
80            98              25       -1              False  plasma
81            98              25       -1              False  plasma
82            98              25       -1              False  plasma
83            98              22       -1               True  plasma
84            98              22       -1               True  plasma
85            98              22       -1               True  plasma
86            98              23       -1               True  plasma
87            98              23       -1               True  plasma
88            98              23       -1               True  plasma
89            98              24       -1               True  plasma
90            98              24       -1               True  plasma
91            98              24       -1               True  plasma
92            98              25       -1               True  plasma
93            98              25       -1               True  plasma
94            98              25       -1               True  plasma
95            106             27       -1              False  plasma
96            106             27       -1              False  plasma
              108             27       -1              False  plasma
97            106             27       -1               True  plasma
98            106             27       -1               True  plasma
              108             27       -1               True  plasma
99            106             27       -1              False  plasma
100           106             27       -1              False  plasma
              108             27       -1              False  plasma
101           106             27       -1               True  plasma
102           106             27       -1               True  plasma
              108             27       -1               True  plasma
103           106             27       -1              False  plasma
104           106             27       -1              False  plasma
              108             27       -1              False  plasma
105           106             27       -1               True  plasma
106           106             27       -1               True  plasma
              108             27       -1               True  plasma

                                                                                                   time  \
timecourse_pk intervention_pk group_pk individual_pk
67            96              20       -1             [0.0, 0.17, 0.33, 0.5, 0.75, 1.0, 1.5, 2.0, 3....
68            94              20       -1             [0.17, 0.33, 0.75, 1.0, 1.5, 2.0, 2.5, 3.0, 4....
69            96              20       -1             [0.0, 0.17, 0.33, 0.5, 0.75, 1.0, 1.5, 2.0, 3....
70            94              20       -1             [0.17, 0.33, 0.75, 1.0, 1.5, 2.0, 2.5, 3.0, 4....
71            98              22       -1             [0.0, 0.125, 0.25, 0.292, 0.333, 0.417, 0.5, 0...
72            98              22       -1             [0.0, 0.125, 0.25, 0.292, 0.333, 0.417, 0.5, 0...
73            98              22       -1             [0.0, 0.125, 0.25, 0.292, 0.333, 0.417, 0.5, 0...
74            98              23       -1             [0.0, 0.125, 0.25, 0.292, 0.333, 0.417, 0.5, 0...
75            98              23       -1             [0.0, 0.125, 0.25, 0.292, 0.333, 0.417, 0.5, 0...
76            98              23       -1             [0.0, 0.125, 0.25, 0.292, 0.333, 0.417, 0.5, 0...
77            98              24       -1             [0.0, 0.125, 0.25, 0.292, 0.333, 0.417, 0.5, 0...
78            98              24       -1             [0.0, 0.125, 0.25, 0.292, 0.333, 0.417, 0.5, 0...
79            98              24       -1             [0.0, 0.125, 0.25, 0.292, 0.333, 0.417, 0.5, 0...
80            98              25       -1             [0.0, 0.125, 0.25, 0.292, 0.333, 0.417, 0.5, 0...
81            98              25       -1             [0.0, 0.125, 0.25, 0.292, 0.333, 0.417, 0.5, 0...
82            98              25       -1             [0.0, 0.125, 0.25, 0.292, 0.333, 0.417, 0.5, 0...
83            98              22       -1             [0.0, 0.125, 0.25, 0.292, 0.333, 0.417, 0.5, 0...
84            98              22       -1             [0.0, 0.125, 0.25, 0.292, 0.333, 0.417, 0.5, 0...
85            98              22       -1             [0.0, 0.125, 0.25, 0.292, 0.333, 0.417, 0.5, 0...
86            98              23       -1             [0.0, 0.125, 0.25, 0.292, 0.333, 0.417, 0.5, 0...
87            98              23       -1             [0.0, 0.125, 0.25, 0.292, 0.333, 0.417, 0.5, 0...
88            98              23       -1             [0.0, 0.125, 0.25, 0.292, 0.333, 0.417, 0.5, 0...
89            98              24       -1             [0.0, 0.125, 0.25, 0.292, 0.333, 0.417, 0.5, 0...
90            98              24       -1             [0.0, 0.125, 0.25, 0.292, 0.333, 0.417, 0.5, 0...
91            98              24       -1             [0.0, 0.125, 0.25, 0.292, 0.333, 0.417, 0.5, 0...
92            98              25       -1             [0.0, 0.125, 0.25, 0.292, 0.333, 0.417, 0.5, 0...
93            98              25       -1             [0.0, 0.125, 0.25, 0.292, 0.333, 0.417, 0.5, 0...
94            98              25       -1             [0.0, 0.125, 0.25, 0.292, 0.333, 0.417, 0.5, 0...
95            106             27       -1             [0.0, 0.25, 0.5, 0.75, 1.0, 1.5, 2.0, 2.5, 3.0...
96            106             27       -1             [0.0, 0.25, 0.5, 0.75, 1.0, 1.5, 2.0, 2.5, 3.0...
              108             27       -1             [0.0, 0.25, 0.5, 0.75, 1.0, 1.5, 2.0, 2.5, 3.0...
97            106             27       -1             [0.0, 0.25, 0.5, 0.75, 1.0, 1.5, 2.0, 2.5, 3.0...
98            106             27       -1             [0.0, 0.25, 0.5, 0.75, 1.0, 1.5, 2.0, 2.5, 3.0...
              108             27       -1             [0.0, 0.25, 0.5, 0.75, 1.0, 1.5, 2.0, 2.5, 3.0...
99            106             27       -1             [0.0, 0.25, 0.5, 0.75, 1.0, 1.5, 2.0, 2.5, 3.0...
100           106             27       -1             [0.0, 0.25, 0.5, 0.75, 1.0, 1.5, 2.0, 2.5, 3.0...
              108             27       -1             [0.0, 0.25, 0.5, 0.75, 1.0, 1.5, 2.0, 2.5, 3.0...
101           106             27       -1             [0.0, 0.25, 0.5, 0.75, 1.0, 1.5, 2.0, 2.5, 3.0...
102           106             27       -1             [0.0, 0.25, 0.5, 0.75, 1.0, 1.5, 2.0, 2.5, 3.0...
              108             27       -1             [0.0, 0.25, 0.5, 0.75, 1.0, 1.5, 2.0, 2.5, 3.0...
103           106             27       -1             [0.0, 0.25, 0.5, 0.75, 1.0, 1.5, 2.0, 2.5, 3.0...
104           106             27       -1             [0.0, 0.25, 0.5, 0.75, 1.0, 1.5, 2.0, 2.5, 3.0...
              108             27       -1             [0.0, 0.25, 0.5, 0.75, 1.0, 1.5, 2.0, 2.5, 3.0...
105           106             27       -1             [0.0, 0.25, 0.5, 0.75, 1.0, 1.5, 2.0, 2.5, 3.0...
106           106             27       -1             [0.0, 0.25, 0.5, 0.75, 1.0, 1.5, 2.0, 2.5, 3.0...
              108             27       -1             [0.0, 0.25, 0.5, 0.75, 1.0, 1.5, 2.0, 2.5, 3.0...

                                                     time_unit  \
timecourse_pk intervention_pk group_pk individual_pk
67            96              20       -1                   hr
68            94              20       -1                   hr
69            96              20       -1                   hr
70            94              20       -1                   hr
71            98              22       -1                   hr
72            98              22       -1                   hr
73            98              22       -1                   hr
74            98              23       -1                   hr
75            98              23       -1                   hr
76            98              23       -1                   hr
77            98              24       -1                   hr
78            98              24       -1                   hr
79            98              24       -1                   hr
80            98              25       -1                   hr
81            98              25       -1                   hr
82            98              25       -1                   hr
83            98              22       -1                   hr
84            98              22       -1                   hr
85            98              22       -1                   hr
86            98              23       -1                   hr
87            98              23       -1                   hr
88            98              23       -1                   hr
89            98              24       -1                   hr
90            98              24       -1                   hr
91            98              24       -1                   hr
92            98              25       -1                   hr
93            98              25       -1                   hr
94            98              25       -1                   hr
95            106             27       -1                   hr
96            106             27       -1                   hr
              108             27       -1                   hr
97            106             27       -1                   hr
98            106             27       -1                   hr
              108             27       -1                   hr
99            106             27       -1                   hr
100           106             27       -1                   hr
              108             27       -1                   hr
101           106             27       -1                   hr
102           106             27       -1                   hr
              108             27       -1                   hr
103           106             27       -1                   hr
104           106             27       -1                   hr
              108             27       -1                   hr
105           106             27       -1                   hr
106           106             27       -1                   hr
              108             27       -1                   hr

                                                     measurement_type choice  \
timecourse_pk intervention_pk group_pk individual_pk
67            96              20       -1               concentration   None
68            94              20       -1               concentration   None
69            96              20       -1               concentration   None
70            94              20       -1               concentration   None
71            98              22       -1               concentration   None
72            98              22       -1               concentration   None
73            98              22       -1               concentration   None
74            98              23       -1               concentration   None
75            98              23       -1               concentration   None
76            98              23       -1               concentration   None
77            98              24       -1               concentration   None
78            98              24       -1               concentration   None
79            98              24       -1               concentration   None
80            98              25       -1               concentration   None
81            98              25       -1               concentration   None
82            98              25       -1               concentration   None
83            98              22       -1               concentration   None
84            98              22       -1               concentration   None
85            98              22       -1               concentration   None
86            98              23       -1               concentration   None
87            98              23       -1               concentration   None
88            98              23       -1               concentration   None
89            98              24       -1               concentration   None
90            98              24       -1               concentration   None
91            98              24       -1               concentration   None
92            98              25       -1               concentration   None
93            98              25       -1               concentration   None
94            98              25       -1               concentration   None
95            106             27       -1               concentration   None
96            106             27       -1               concentration   None
              108             27       -1               concentration   None
97            106             27       -1               concentration   None
98            106             27       -1               concentration   None
              108             27       -1               concentration   None
99            106             27       -1               concentration   None
100           106             27       -1               concentration   None
              108             27       -1               concentration   None
101           106             27       -1               concentration   None
102           106             27       -1               concentration   None
              108             27       -1               concentration   None
103           106             27       -1             metabolic ratio   None
104           106             27       -1             metabolic ratio   None
              108             27       -1             metabolic ratio   None
105           106             27       -1             metabolic ratio   None
106           106             27       -1             metabolic ratio   None
              108             27       -1             metabolic ratio   None

                                                                    substance  \
timecourse_pk intervention_pk group_pk individual_pk
67            96              20       -1                           midazolam
68            94              20       -1                           midazolam
69            96              20       -1                           midazolam
70            94              20       -1                           midazolam
71            98              22       -1                         paracetamol
72            98              22       -1             paracetamol glucuronide
73            98              22       -1                 paracetamol sulfate
74            98              23       -1                         paracetamol
75            98              23       -1             paracetamol glucuronide
76            98              23       -1                 paracetamol sulfate
77            98              24       -1                         paracetamol
78            98              24       -1             paracetamol glucuronide
79            98              24       -1                 paracetamol sulfate
80            98              25       -1                         paracetamol
81            98              25       -1             paracetamol glucuronide
82            98              25       -1                 paracetamol sulfate
83            98              22       -1                         paracetamol